export interface EmojiItem {
  emoji: string;
  name: string;
  category: string;
}

export const EMOJI_CATEGORIES = [
  "Smileys",
  "People",
  "Animals",
  "Food",
  "Activities",
  "Travel",
  "Objects",
  "Symbols",
  "Flags",
] as const;

export const QUICK_REACTIONS = ["❤️", "😂", "😮", "😢", "😡", "👍"];

export const EMOJI_DATA: EmojiItem[] = [
  // ─────────────── Smileys & Emotion ───────────────
  { emoji: "😀", name: "grinning", category: "Smileys" },
  { emoji: "😃", name: "smiley happy", category: "Smileys" },
  { emoji: "😄", name: "smile happy", category: "Smileys" },
  { emoji: "😁", name: "grin beaming", category: "Smileys" },
  { emoji: "😆", name: "laughing satisfied", category: "Smileys" },
  { emoji: "😅", name: "sweat smile", category: "Smileys" },
  { emoji: "🤣", name: "rofl rolling laughing", category: "Smileys" },
  { emoji: "😂", name: "joy laughing tears", category: "Smileys" },
  { emoji: "🙂", name: "slightly smiling", category: "Smileys" },
  { emoji: "🙃", name: "upside down", category: "Smileys" },
  { emoji: "🫠", name: "melting", category: "Smileys" },
  { emoji: "😊", name: "blush smiling", category: "Smileys" },
  { emoji: "😇", name: "innocent halo angel", category: "Smileys" },
  { emoji: "🥰", name: "smiling hearts love", category: "Smileys" },
  { emoji: "😍", name: "heart eyes love", category: "Smileys" },
  { emoji: "🤩", name: "star struck", category: "Smileys" },
  { emoji: "😘", name: "kissing heart blow", category: "Smileys" },
  { emoji: "😗", name: "kissing", category: "Smileys" },
  { emoji: "☺️", name: "smiling relaxed", category: "Smileys" },
  { emoji: "😚", name: "kissing closed eyes", category: "Smileys" },
  { emoji: "😙", name: "kissing smiling eyes", category: "Smileys" },
  { emoji: "🥲", name: "smiling tear happy cry", category: "Smileys" },
  { emoji: "😋", name: "yum tasty savoring", category: "Smileys" },
  { emoji: "😛", name: "tongue out", category: "Smileys" },
  { emoji: "😜", name: "winking tongue", category: "Smileys" },
  { emoji: "🤪", name: "zany goofy", category: "Smileys" },
  { emoji: "😝", name: "squinting tongue", category: "Smileys" },
  { emoji: "🤑", name: "money mouth", category: "Smileys" },
  { emoji: "🤗", name: "hugging hug", category: "Smileys" },
  { emoji: "🤭", name: "hand over mouth giggle", category: "Smileys" },
  { emoji: "🫢", name: "gasp shocked hand", category: "Smileys" },
  { emoji: "🫣", name: "peeking", category: "Smileys" },
  { emoji: "🤫", name: "shushing quiet", category: "Smileys" },
  { emoji: "🤔", name: "thinking", category: "Smileys" },
  { emoji: "🫡", name: "saluting", category: "Smileys" },
  { emoji: "🤐", name: "zipper mouth", category: "Smileys" },
  { emoji: "🤨", name: "raised eyebrow skeptic", category: "Smileys" },
  { emoji: "😐", name: "neutral", category: "Smileys" },
  { emoji: "😑", name: "expressionless", category: "Smileys" },
  { emoji: "😶", name: "no mouth speechless", category: "Smileys" },
  { emoji: "🫥", name: "dotted line invisible", category: "Smileys" },
  { emoji: "😏", name: "smirk", category: "Smileys" },
  { emoji: "😒", name: "unamused meh", category: "Smileys" },
  { emoji: "🙄", name: "eye roll", category: "Smileys" },
  { emoji: "😬", name: "grimacing awkward", category: "Smileys" },
  { emoji: "🫨", name: "shaking face", category: "Smileys" },
  { emoji: "😮‍💨", name: "exhale relief sigh", category: "Smileys" },
  { emoji: "🤥", name: "lying pinocchio", category: "Smileys" },
  { emoji: "😌", name: "relieved calm", category: "Smileys" },
  { emoji: "😔", name: "pensive sad", category: "Smileys" },
  { emoji: "😪", name: "sleepy", category: "Smileys" },
  { emoji: "🤤", name: "drooling", category: "Smileys" },
  { emoji: "😴", name: "sleeping zzz", category: "Smileys" },
  { emoji: "😷", name: "mask sick", category: "Smileys" },
  { emoji: "🤒", name: "thermometer sick", category: "Smileys" },
  { emoji: "🤕", name: "head bandage hurt", category: "Smileys" },
  { emoji: "🤢", name: "nauseated sick", category: "Smileys" },
  { emoji: "🤮", name: "vomiting puke", category: "Smileys" },
  { emoji: "🤧", name: "sneezing", category: "Smileys" },
  { emoji: "🥵", name: "hot heat sweating", category: "Smileys" },
  { emoji: "🥶", name: "cold freezing", category: "Smileys" },
  { emoji: "🥴", name: "woozy dizzy drunk", category: "Smileys" },
  { emoji: "😵", name: "dizzy face", category: "Smileys" },
  { emoji: "😵‍💫", name: "spiral eyes confused", category: "Smileys" },
  { emoji: "🤯", name: "mind blown exploding", category: "Smileys" },
  { emoji: "🤠", name: "cowboy", category: "Smileys" },
  { emoji: "🥳", name: "partying celebrate", category: "Smileys" },
  { emoji: "🥸", name: "disguise glasses", category: "Smileys" },
  { emoji: "😎", name: "cool sunglasses", category: "Smileys" },
  { emoji: "🤓", name: "nerd glasses", category: "Smileys" },
  { emoji: "🧐", name: "monocle inspect", category: "Smileys" },
  { emoji: "😕", name: "confused", category: "Smileys" },
  { emoji: "🫤", name: "diagonal mouth meh", category: "Smileys" },
  { emoji: "😟", name: "worried", category: "Smileys" },
  { emoji: "🙁", name: "slightly frowning", category: "Smileys" },
  { emoji: "☹️", name: "frowning sad", category: "Smileys" },
  { emoji: "😮", name: "open mouth wow", category: "Smileys" },
  { emoji: "😯", name: "hushed surprised", category: "Smileys" },
  { emoji: "😲", name: "astonished shocked", category: "Smileys" },
  { emoji: "😳", name: "flushed embarrassed", category: "Smileys" },
  { emoji: "🥺", name: "pleading puppy eyes", category: "Smileys" },
  { emoji: "🥹", name: "holding back tears", category: "Smileys" },
  { emoji: "😦", name: "frowning open", category: "Smileys" },
  { emoji: "😧", name: "anguished", category: "Smileys" },
  { emoji: "😨", name: "fearful scared", category: "Smileys" },
  { emoji: "😰", name: "anxious sweat", category: "Smileys" },
  { emoji: "😥", name: "sad relieved", category: "Smileys" },
  { emoji: "😢", name: "crying tear sad", category: "Smileys" },
  { emoji: "😭", name: "sobbing loudly crying", category: "Smileys" },
  { emoji: "😱", name: "screaming fear", category: "Smileys" },
  { emoji: "😖", name: "confounded", category: "Smileys" },
  { emoji: "😣", name: "persevering", category: "Smileys" },
  { emoji: "😞", name: "disappointed", category: "Smileys" },
  { emoji: "😓", name: "downcast sweat", category: "Smileys" },
  { emoji: "😩", name: "weary tired", category: "Smileys" },
  { emoji: "😫", name: "tired exhausted", category: "Smileys" },
  { emoji: "🥱", name: "yawning bored", category: "Smileys" },
  { emoji: "😤", name: "huffing triumph", category: "Smileys" },
  { emoji: "😡", name: "pouting angry red", category: "Smileys" },
  { emoji: "😠", name: "angry mad", category: "Smileys" },
  { emoji: "🤬", name: "cursing swearing", category: "Smileys" },
  { emoji: "😈", name: "smiling devil horns", category: "Smileys" },
  { emoji: "👿", name: "angry devil imp", category: "Smileys" },
  { emoji: "💀", name: "skull dead", category: "Smileys" },
  { emoji: "☠️", name: "skull crossbones", category: "Smileys" },
  { emoji: "💩", name: "poop", category: "Smileys" },
  { emoji: "🤡", name: "clown", category: "Smileys" },
  { emoji: "👹", name: "ogre", category: "Smileys" },
  { emoji: "👺", name: "goblin", category: "Smileys" },
  { emoji: "👻", name: "ghost boo", category: "Smileys" },
  { emoji: "👽", name: "alien", category: "Smileys" },
  { emoji: "👾", name: "space invader", category: "Smileys" },
  { emoji: "🤖", name: "robot", category: "Smileys" },
  { emoji: "🎃", name: "jack o lantern pumpkin", category: "Smileys" },
  { emoji: "😺", name: "grinning cat", category: "Smileys" },
  { emoji: "😸", name: "grinning cat smile", category: "Smileys" },
  { emoji: "😹", name: "cat joy tears", category: "Smileys" },
  { emoji: "😻", name: "cat heart eyes", category: "Smileys" },
  { emoji: "😼", name: "cat smirk", category: "Smileys" },
  { emoji: "😽", name: "kissing cat", category: "Smileys" },
  { emoji: "🙀", name: "weary cat", category: "Smileys" },
  { emoji: "😿", name: "crying cat", category: "Smileys" },
  { emoji: "😾", name: "pouting cat", category: "Smileys" },

  // ─────────────── People & Body ───────────────
  { emoji: "👋", name: "waving hand hi bye", category: "People" },
  { emoji: "🤚", name: "raised back hand", category: "People" },
  { emoji: "🖐️", name: "hand fingers splayed", category: "People" },
  { emoji: "✋", name: "raised hand stop", category: "People" },
  { emoji: "🖖", name: "vulcan salute spock", category: "People" },
  { emoji: "🫱", name: "rightwards hand", category: "People" },
  { emoji: "🫲", name: "leftwards hand", category: "People" },
  { emoji: "🫳", name: "palm down", category: "People" },
  { emoji: "🫴", name: "palm up", category: "People" },
  { emoji: "👌", name: "ok hand", category: "People" },
  { emoji: "🤌", name: "pinched fingers italian", category: "People" },
  { emoji: "🤏", name: "pinching small", category: "People" },
  { emoji: "✌️", name: "victory peace", category: "People" },
  { emoji: "🤞", name: "crossed fingers luck", category: "People" },
  { emoji: "🫰", name: "finger heart", category: "People" },
  { emoji: "🤟", name: "love you gesture", category: "People" },
  { emoji: "🤘", name: "rock on horns", category: "People" },
  { emoji: "🤙", name: "call me shaka", category: "People" },
  { emoji: "👈", name: "pointing left", category: "People" },
  { emoji: "👉", name: "pointing right", category: "People" },
  { emoji: "👆", name: "pointing up", category: "People" },
  { emoji: "👇", name: "pointing down", category: "People" },
  { emoji: "☝️", name: "index up", category: "People" },
  { emoji: "🫵", name: "pointing at you", category: "People" },
  { emoji: "👍", name: "thumbs up like yes", category: "People" },
  { emoji: "👎", name: "thumbs down dislike no", category: "People" },
  { emoji: "✊", name: "raised fist", category: "People" },
  { emoji: "👊", name: "fist bump punch", category: "People" },
  { emoji: "🤛", name: "left fist", category: "People" },
  { emoji: "🤜", name: "right fist", category: "People" },
  { emoji: "👏", name: "clapping applause", category: "People" },
  { emoji: "🙌", name: "raising hands praise", category: "People" },
  { emoji: "🫶", name: "heart hands love", category: "People" },
  { emoji: "👐", name: "open hands", category: "People" },
  { emoji: "🤲", name: "palms up together", category: "People" },
  { emoji: "🤝", name: "handshake deal", category: "People" },
  { emoji: "🙏", name: "folded hands pray thanks", category: "People" },
  { emoji: "✍️", name: "writing hand", category: "People" },
  { emoji: "💅", name: "nail polish manicure", category: "People" },
  { emoji: "🤳", name: "selfie", category: "People" },
  { emoji: "💪", name: "flexed biceps strong muscle", category: "People" },
  { emoji: "🦾", name: "mechanical arm", category: "People" },
  { emoji: "🦵", name: "leg", category: "People" },
  { emoji: "🦶", name: "foot", category: "People" },
  { emoji: "👂", name: "ear", category: "People" },
  { emoji: "👃", name: "nose", category: "People" },
  { emoji: "🧠", name: "brain", category: "People" },
  { emoji: "🫀", name: "anatomical heart", category: "People" },
  { emoji: "🦷", name: "tooth", category: "People" },
  { emoji: "👀", name: "eyes looking", category: "People" },
  { emoji: "👁️", name: "eye", category: "People" },
  { emoji: "👅", name: "tongue", category: "People" },
  { emoji: "👄", name: "mouth lips", category: "People" },
  { emoji: "🫦", name: "biting lip", category: "People" },
  { emoji: "👶", name: "baby", category: "People" },
  { emoji: "🧒", name: "child", category: "People" },
  { emoji: "👦", name: "boy", category: "People" },
  { emoji: "👧", name: "girl", category: "People" },
  { emoji: "🧑", name: "person adult", category: "People" },
  { emoji: "👨", name: "man", category: "People" },
  { emoji: "👩", name: "woman", category: "People" },
  { emoji: "🧔", name: "person beard", category: "People" },
  { emoji: "👱", name: "blond person", category: "People" },
  { emoji: "👴", name: "old man grandpa", category: "People" },
  { emoji: "👵", name: "old woman grandma", category: "People" },
  { emoji: "🧓", name: "older person", category: "People" },
  { emoji: "🙍", name: "person frowning", category: "People" },
  { emoji: "🙎", name: "person pouting", category: "People" },
  { emoji: "🙅", name: "no gesture", category: "People" },
  { emoji: "🙆", name: "ok gesture person", category: "People" },
  { emoji: "💁", name: "tipping hand info", category: "People" },
  { emoji: "🙋", name: "raising hand", category: "People" },
  { emoji: "🧏", name: "deaf person", category: "People" },
  { emoji: "🙇", name: "bowing sorry", category: "People" },
  { emoji: "🤦", name: "facepalm", category: "People" },
  { emoji: "🤷", name: "shrug", category: "People" },
  { emoji: "🧑‍⚕️", name: "health worker doctor", category: "People" },
  { emoji: "🧑‍🏫", name: "teacher", category: "People" },
  { emoji: "🧑‍🍳", name: "cook chef", category: "People" },
  { emoji: "🧑‍🌾", name: "farmer", category: "People" },
  { emoji: "🧑‍🚀", name: "astronaut", category: "People" },
  { emoji: "🧑‍🚒", name: "firefighter", category: "People" },
  { emoji: "👮", name: "police officer", category: "People" },
  { emoji: "🕵️", name: "detective spy", category: "People" },
  { emoji: "💂", name: "guard", category: "People" },
  { emoji: "👷", name: "construction worker", category: "People" },
  { emoji: "🤴", name: "prince", category: "People" },
  { emoji: "👸", name: "princess", category: "People" },
  { emoji: "👰", name: "bride veil", category: "People" },
  { emoji: "🤵", name: "tuxedo groom", category: "People" },
  { emoji: "🦸", name: "superhero", category: "People" },
  { emoji: "🦹", name: "supervillain", category: "People" },
  { emoji: "🧙", name: "mage wizard", category: "People" },
  { emoji: "🧚", name: "fairy", category: "People" },
  { emoji: "🧛", name: "vampire", category: "People" },
  { emoji: "🧜", name: "merperson mermaid", category: "People" },
  { emoji: "🧝", name: "elf", category: "People" },
  { emoji: "🎅", name: "santa claus", category: "People" },
  { emoji: "🤶", name: "mrs claus", category: "People" },
  { emoji: "👼", name: "baby angel", category: "People" },
  { emoji: "🤰", name: "pregnant", category: "People" },
  { emoji: "🤱", name: "breastfeeding", category: "People" },
  { emoji: "🧑‍🍼", name: "feeding baby", category: "People" },
  { emoji: "💃", name: "dancer woman dancing", category: "People" },
  { emoji: "🕺", name: "man dancing", category: "People" },
  { emoji: "👯", name: "dancers bunny ears", category: "People" },
  { emoji: "🧖", name: "sauna steam", category: "People" },
  { emoji: "🧗", name: "climbing", category: "People" },
  { emoji: "🤺", name: "fencing", category: "People" },
  { emoji: "🏇", name: "horse racing", category: "People" },
  { emoji: "🏂", name: "snowboarder", category: "People" },
  { emoji: "🏌️", name: "golfer", category: "People" },
  { emoji: "🏄", name: "surfer", category: "People" },
  { emoji: "🚣", name: "rowboat", category: "People" },
  { emoji: "🏊", name: "swimmer", category: "People" },
  { emoji: "🚴", name: "biking cyclist", category: "People" },
  { emoji: "🧘", name: "meditation yoga lotus", category: "People" },
  { emoji: "👫", name: "couple holding hands", category: "People" },
  { emoji: "💏", name: "kiss couple", category: "People" },
  { emoji: "💑", name: "couple with heart", category: "People" },
  { emoji: "👪", name: "family", category: "People" },
  { emoji: "🗣️", name: "speaking head", category: "People" },
  { emoji: "👤", name: "silhouette person", category: "People" },
  { emoji: "👥", name: "silhouette people", category: "People" },

  // ─────────────── Animals & Nature ───────────────
  { emoji: "🐶", name: "dog puppy", category: "Animals" },
  { emoji: "🐱", name: "cat", category: "Animals" },
  { emoji: "🐭", name: "mouse", category: "Animals" },
  { emoji: "🐹", name: "hamster", category: "Animals" },
  { emoji: "🐰", name: "rabbit bunny", category: "Animals" },
  { emoji: "🦊", name: "fox", category: "Animals" },
  { emoji: "🐻", name: "bear", category: "Animals" },
  { emoji: "🐼", name: "panda", category: "Animals" },
  { emoji: "🐻‍❄️", name: "polar bear", category: "Animals" },
  { emoji: "🐨", name: "koala", category: "Animals" },
  { emoji: "🐯", name: "tiger", category: "Animals" },
  { emoji: "🦁", name: "lion", category: "Animals" },
  { emoji: "🐮", name: "cow", category: "Animals" },
  { emoji: "🐷", name: "pig", category: "Animals" },
  { emoji: "🐽", name: "pig nose", category: "Animals" },
  { emoji: "🐸", name: "frog", category: "Animals" },
  { emoji: "🐵", name: "monkey face", category: "Animals" },
  { emoji: "🙈", name: "see no evil monkey", category: "Animals" },
  { emoji: "🙉", name: "hear no evil monkey", category: "Animals" },
  { emoji: "🙊", name: "speak no evil monkey", category: "Animals" },
  { emoji: "🐒", name: "monkey", category: "Animals" },
  { emoji: "🐔", name: "chicken", category: "Animals" },
  { emoji: "🐧", name: "penguin", category: "Animals" },
  { emoji: "🐦", name: "bird", category: "Animals" },
  { emoji: "🐤", name: "baby chick", category: "Animals" },
  { emoji: "🦆", name: "duck", category: "Animals" },
  { emoji: "🦅", name: "eagle", category: "Animals" },
  { emoji: "🦉", name: "owl", category: "Animals" },
  { emoji: "🦇", name: "bat", category: "Animals" },
  { emoji: "🐺", name: "wolf", category: "Animals" },
  { emoji: "🐗", name: "boar", category: "Animals" },
  { emoji: "🐴", name: "horse face", category: "Animals" },
  { emoji: "🦄", name: "unicorn", category: "Animals" },
  { emoji: "🐝", name: "bee honeybee", category: "Animals" },
  { emoji: "🪲", name: "beetle bug", category: "Animals" },
  { emoji: "🐛", name: "caterpillar bug", category: "Animals" },
  { emoji: "🦋", name: "butterfly", category: "Animals" },
  { emoji: "🐌", name: "snail", category: "Animals" },
  { emoji: "🐞", name: "ladybug", category: "Animals" },
  { emoji: "🐜", name: "ant", category: "Animals" },
  { emoji: "🦟", name: "mosquito", category: "Animals" },
  { emoji: "🕷️", name: "spider", category: "Animals" },
  { emoji: "🦂", name: "scorpion", category: "Animals" },
  { emoji: "🐢", name: "turtle", category: "Animals" },
  { emoji: "🐍", name: "snake", category: "Animals" },
  { emoji: "🦎", name: "lizard", category: "Animals" },
  { emoji: "🦖", name: "t-rex dinosaur", category: "Animals" },
  { emoji: "🦕", name: "sauropod dinosaur", category: "Animals" },
  { emoji: "🐙", name: "octopus", category: "Animals" },
  { emoji: "🦑", name: "squid", category: "Animals" },
  { emoji: "🦐", name: "shrimp", category: "Animals" },
  { emoji: "🦀", name: "crab", category: "Animals" },
  { emoji: "🐡", name: "blowfish pufferfish", category: "Animals" },
  { emoji: "🐠", name: "tropical fish", category: "Animals" },
  { emoji: "🐟", name: "fish", category: "Animals" },
  { emoji: "🐬", name: "dolphin", category: "Animals" },
  { emoji: "🐳", name: "spouting whale", category: "Animals" },
  { emoji: "🐋", name: "whale", category: "Animals" },
  { emoji: "🦈", name: "shark", category: "Animals" },
  { emoji: "🐊", name: "crocodile", category: "Animals" },
  { emoji: "🐅", name: "tiger full", category: "Animals" },
  { emoji: "🐆", name: "leopard", category: "Animals" },
  { emoji: "🦓", name: "zebra", category: "Animals" },
  { emoji: "🦍", name: "gorilla", category: "Animals" },
  { emoji: "🦧", name: "orangutan", category: "Animals" },
  { emoji: "🐘", name: "elephant", category: "Animals" },
  { emoji: "🦛", name: "hippo", category: "Animals" },
  { emoji: "🦏", name: "rhino", category: "Animals" },
  { emoji: "🐪", name: "camel", category: "Animals" },
  { emoji: "🦒", name: "giraffe", category: "Animals" },
  { emoji: "🦘", name: "kangaroo", category: "Animals" },
  { emoji: "🐃", name: "water buffalo", category: "Animals" },
  { emoji: "🐂", name: "ox", category: "Animals" },
  { emoji: "🐄", name: "cow full", category: "Animals" },
  { emoji: "🐎", name: "horse running", category: "Animals" },
  { emoji: "🐖", name: "pig full", category: "Animals" },
  { emoji: "🐏", name: "ram", category: "Animals" },
  { emoji: "🐑", name: "sheep", category: "Animals" },
  { emoji: "🦙", name: "llama", category: "Animals" },
  { emoji: "🐐", name: "goat", category: "Animals" },
  { emoji: "🦌", name: "deer", category: "Animals" },
  { emoji: "🐕", name: "dog full", category: "Animals" },
  { emoji: "🐩", name: "poodle", category: "Animals" },
  { emoji: "🦮", name: "guide dog", category: "Animals" },
  { emoji: "🐈", name: "cat full", category: "Animals" },
  { emoji: "🐈‍⬛", name: "black cat", category: "Animals" },
  { emoji: "🐓", name: "rooster", category: "Animals" },
  { emoji: "🦃", name: "turkey", category: "Animals" },
  { emoji: "🦚", name: "peacock", category: "Animals" },
  { emoji: "🦜", name: "parrot", category: "Animals" },
  { emoji: "🦢", name: "swan", category: "Animals" },
  { emoji: "🦩", name: "flamingo", category: "Animals" },
  { emoji: "🕊️", name: "dove peace", category: "Animals" },
  { emoji: "🐇", name: "rabbit full", category: "Animals" },
  { emoji: "🦝", name: "raccoon", category: "Animals" },
  { emoji: "🦨", name: "skunk", category: "Animals" },
  { emoji: "🦡", name: "badger", category: "Animals" },
  { emoji: "🦦", name: "otter", category: "Animals" },
  { emoji: "🦥", name: "sloth", category: "Animals" },
  { emoji: "🐁", name: "mouse full", category: "Animals" },
  { emoji: "🐀", name: "rat", category: "Animals" },
  { emoji: "🐿️", name: "chipmunk squirrel", category: "Animals" },
  { emoji: "🦔", name: "hedgehog", category: "Animals" },
  { emoji: "🐾", name: "paw prints", category: "Animals" },
  { emoji: "🐉", name: "dragon", category: "Animals" },
  { emoji: "🐲", name: "dragon face", category: "Animals" },
  { emoji: "🌵", name: "cactus", category: "Animals" },
  { emoji: "🎄", name: "christmas tree", category: "Animals" },
  { emoji: "🌲", name: "evergreen tree", category: "Animals" },
  { emoji: "🌳", name: "deciduous tree", category: "Animals" },
  { emoji: "🌴", name: "palm tree", category: "Animals" },
  { emoji: "🌱", name: "seedling sprout", category: "Animals" },
  { emoji: "🌿", name: "herb leaves", category: "Animals" },
  { emoji: "☘️", name: "shamrock", category: "Animals" },
  { emoji: "🍀", name: "four leaf clover luck", category: "Animals" },
  { emoji: "🎍", name: "bamboo", category: "Animals" },
  { emoji: "🍃", name: "leaves wind", category: "Animals" },
  { emoji: "🍂", name: "fallen leaves autumn", category: "Animals" },
  { emoji: "🍁", name: "maple leaf", category: "Animals" },
  { emoji: "🌾", name: "wheat", category: "Animals" },
  { emoji: "🌺", name: "hibiscus flower", category: "Animals" },
  { emoji: "🌸", name: "cherry blossom", category: "Animals" },
  { emoji: "🌼", name: "blossom flower", category: "Animals" },
  { emoji: "🌻", name: "sunflower", category: "Animals" },
  { emoji: "🌹", name: "rose", category: "Animals" },
  { emoji: "🥀", name: "wilted rose", category: "Animals" },
  { emoji: "🌷", name: "tulip", category: "Animals" },
  { emoji: "💐", name: "bouquet flowers", category: "Animals" },
  { emoji: "🪻", name: "hyacinth", category: "Animals" },
  { emoji: "🪷", name: "lotus", category: "Animals" },
  { emoji: "🍄", name: "mushroom", category: "Animals" },
  { emoji: "🌰", name: "chestnut", category: "Animals" },

  // ─────────────── Food & Drink ───────────────
  { emoji: "🍏", name: "green apple", category: "Food" },
  { emoji: "🍎", name: "red apple", category: "Food" },
  { emoji: "🍐", name: "pear", category: "Food" },
  { emoji: "🍊", name: "tangerine orange", category: "Food" },
  { emoji: "🍋", name: "lemon", category: "Food" },
  { emoji: "🍌", name: "banana", category: "Food" },
  { emoji: "🍉", name: "watermelon", category: "Food" },
  { emoji: "🍇", name: "grapes", category: "Food" },
  { emoji: "🍓", name: "strawberry", category: "Food" },
  { emoji: "🫐", name: "blueberries", category: "Food" },
  { emoji: "🍈", name: "melon", category: "Food" },
  { emoji: "🍒", name: "cherries", category: "Food" },
  { emoji: "🍑", name: "peach", category: "Food" },
  { emoji: "🥭", name: "mango", category: "Food" },
  { emoji: "🍍", name: "pineapple", category: "Food" },
  { emoji: "🥥", name: "coconut", category: "Food" },
  { emoji: "🥝", name: "kiwi", category: "Food" },
  { emoji: "🍅", name: "tomato", category: "Food" },
  { emoji: "🍆", name: "eggplant", category: "Food" },
  { emoji: "🥑", name: "avocado", category: "Food" },
  { emoji: "🥦", name: "broccoli", category: "Food" },
  { emoji: "🥬", name: "leafy greens lettuce", category: "Food" },
  { emoji: "🥒", name: "cucumber", category: "Food" },
  { emoji: "🌶️", name: "hot pepper chili", category: "Food" },
  { emoji: "🫑", name: "bell pepper", category: "Food" },
  { emoji: "🌽", name: "corn", category: "Food" },
  { emoji: "🥕", name: "carrot", category: "Food" },
  { emoji: "🫒", name: "olive", category: "Food" },
  { emoji: "🧄", name: "garlic", category: "Food" },
  { emoji: "🧅", name: "onion", category: "Food" },
  { emoji: "🥔", name: "potato", category: "Food" },
  { emoji: "🍠", name: "sweet potato", category: "Food" },
  { emoji: "🥐", name: "croissant", category: "Food" },
  { emoji: "🥯", name: "bagel", category: "Food" },
  { emoji: "🍞", name: "bread", category: "Food" },
  { emoji: "🥖", name: "baguette", category: "Food" },
  { emoji: "🥨", name: "pretzel", category: "Food" },
  { emoji: "🧀", name: "cheese", category: "Food" },
  { emoji: "🥚", name: "egg", category: "Food" },
  { emoji: "🍳", name: "fried egg cooking", category: "Food" },
  { emoji: "🧈", name: "butter", category: "Food" },
  { emoji: "🥞", name: "pancakes", category: "Food" },
  { emoji: "🧇", name: "waffle", category: "Food" },
  { emoji: "🥓", name: "bacon", category: "Food" },
  { emoji: "🥩", name: "steak meat", category: "Food" },
  { emoji: "🍗", name: "poultry leg drumstick", category: "Food" },
  { emoji: "🍖", name: "meat on bone", category: "Food" },
  { emoji: "🌭", name: "hot dog", category: "Food" },
  { emoji: "🍔", name: "hamburger burger", category: "Food" },
  { emoji: "🍟", name: "fries", category: "Food" },
  { emoji: "🍕", name: "pizza", category: "Food" },
  { emoji: "🥪", name: "sandwich", category: "Food" },
  { emoji: "🌮", name: "taco", category: "Food" },
  { emoji: "🌯", name: "burrito", category: "Food" },
  { emoji: "🫔", name: "tamale", category: "Food" },
  { emoji: "🥙", name: "stuffed flatbread", category: "Food" },
  { emoji: "🧆", name: "falafel", category: "Food" },
  { emoji: "🥘", name: "shallow pan paella", category: "Food" },
  { emoji: "🍲", name: "pot of food stew", category: "Food" },
  { emoji: "🍜", name: "ramen noodles", category: "Food" },
  { emoji: "🍝", name: "spaghetti pasta", category: "Food" },
  { emoji: "🍛", name: "curry rice", category: "Food" },
  { emoji: "🍣", name: "sushi", category: "Food" },
  { emoji: "🍱", name: "bento box", category: "Food" },
  { emoji: "🍤", name: "fried shrimp tempura", category: "Food" },
  { emoji: "🍙", name: "rice ball", category: "Food" },
  { emoji: "🍚", name: "cooked rice", category: "Food" },
  { emoji: "🍘", name: "rice cracker", category: "Food" },
  { emoji: "🥟", name: "dumpling", category: "Food" },
  { emoji: "🦪", name: "oyster", category: "Food" },
  { emoji: "🍥", name: "fish cake", category: "Food" },
  { emoji: "🥠", name: "fortune cookie", category: "Food" },
  { emoji: "🥮", name: "moon cake", category: "Food" },
  { emoji: "🍢", name: "oden skewer", category: "Food" },
  { emoji: "🍡", name: "dango", category: "Food" },
  { emoji: "🍧", name: "shaved ice", category: "Food" },
  { emoji: "🍨", name: "ice cream", category: "Food" },
  { emoji: "🍦", name: "soft serve icecream", category: "Food" },
  { emoji: "🥧", name: "pie", category: "Food" },
  { emoji: "🧁", name: "cupcake", category: "Food" },
  { emoji: "🍰", name: "shortcake slice", category: "Food" },
  { emoji: "🎂", name: "birthday cake", category: "Food" },
  { emoji: "🍮", name: "custard flan", category: "Food" },
  { emoji: "🍭", name: "lollipop", category: "Food" },
  { emoji: "🍬", name: "candy", category: "Food" },
  { emoji: "🍫", name: "chocolate", category: "Food" },
  { emoji: "🍿", name: "popcorn", category: "Food" },
  { emoji: "🍩", name: "donut", category: "Food" },
  { emoji: "🍪", name: "cookie", category: "Food" },
  { emoji: "🌰", name: "chestnut nut", category: "Food" },
  { emoji: "🥜", name: "peanuts", category: "Food" },
  { emoji: "🍯", name: "honey", category: "Food" },
  { emoji: "🥛", name: "milk glass", category: "Food" },
  { emoji: "🍼", name: "baby bottle", category: "Food" },
  { emoji: "☕", name: "coffee hot", category: "Food" },
  { emoji: "🫖", name: "teapot", category: "Food" },
  { emoji: "🍵", name: "tea green", category: "Food" },
  { emoji: "🧃", name: "juice box", category: "Food" },
  { emoji: "🥤", name: "cup straw soda", category: "Food" },
  { emoji: "🧋", name: "bubble tea boba", category: "Food" },
  { emoji: "🍶", name: "sake", category: "Food" },
  { emoji: "🍺", name: "beer", category: "Food" },
  { emoji: "🍻", name: "cheers beers", category: "Food" },
  { emoji: "🥂", name: "clinking glasses champagne", category: "Food" },
  { emoji: "🍷", name: "wine", category: "Food" },
  { emoji: "🥃", name: "whiskey tumbler", category: "Food" },
  { emoji: "🍸", name: "cocktail martini", category: "Food" },
  { emoji: "🍹", name: "tropical drink", category: "Food" },
  { emoji: "🧉", name: "mate", category: "Food" },
  { emoji: "🍾", name: "champagne bottle", category: "Food" },
  { emoji: "🥄", name: "spoon", category: "Food" },
  { emoji: "🍴", name: "fork and knife", category: "Food" },
  { emoji: "🍽️", name: "plate cutlery", category: "Food" },
  { emoji: "🥢", name: "chopsticks", category: "Food" },
  { emoji: "🧂", name: "salt", category: "Food" },

  // ─────────────── Activities ───────────────
  { emoji: "⚽", name: "soccer football", category: "Activities" },
  { emoji: "🏀", name: "basketball", category: "Activities" },
  { emoji: "🏈", name: "american football", category: "Activities" },
  { emoji: "⚾", name: "baseball", category: "Activities" },
  { emoji: "🥎", name: "softball", category: "Activities" },
  { emoji: "🎾", name: "tennis", category: "Activities" },
  { emoji: "🏐", name: "volleyball", category: "Activities" },
  { emoji: "🏉", name: "rugby", category: "Activities" },
  { emoji: "🥏", name: "frisbee", category: "Activities" },
  { emoji: "🎱", name: "8 ball pool", category: "Activities" },
  { emoji: "🪀", name: "yo-yo", category: "Activities" },
  { emoji: "🏓", name: "ping pong table tennis", category: "Activities" },
  { emoji: "🏸", name: "badminton", category: "Activities" },
  { emoji: "🏒", name: "ice hockey", category: "Activities" },
  { emoji: "🏑", name: "field hockey", category: "Activities" },
  { emoji: "🥍", name: "lacrosse", category: "Activities" },
  { emoji: "🏏", name: "cricket", category: "Activities" },
  { emoji: "🪃", name: "boomerang", category: "Activities" },
  { emoji: "🥅", name: "goal net", category: "Activities" },
  { emoji: "⛳", name: "golf flag", category: "Activities" },
  { emoji: "🪁", name: "kite", category: "Activities" },
  { emoji: "🏹", name: "bow and arrow archery", category: "Activities" },
  { emoji: "🎣", name: "fishing", category: "Activities" },
  { emoji: "🤿", name: "diving mask", category: "Activities" },
  { emoji: "🥊", name: "boxing glove", category: "Activities" },
  { emoji: "🥋", name: "martial arts uniform", category: "Activities" },
  { emoji: "🎽", name: "running shirt", category: "Activities" },
  { emoji: "🛹", name: "skateboard", category: "Activities" },
  { emoji: "🛼", name: "roller skate", category: "Activities" },
  { emoji: "🛷", name: "sled", category: "Activities" },
  { emoji: "⛸️", name: "ice skate", category: "Activities" },
  { emoji: "🥌", name: "curling stone", category: "Activities" },
  { emoji: "🎿", name: "skis", category: "Activities" },
  { emoji: "⛷️", name: "skier", category: "Activities" },
  { emoji: "🏆", name: "trophy win", category: "Activities" },
  { emoji: "🥇", name: "gold medal first", category: "Activities" },
  { emoji: "🥈", name: "silver medal second", category: "Activities" },
  { emoji: "🥉", name: "bronze medal third", category: "Activities" },
  { emoji: "🏅", name: "sports medal", category: "Activities" },
  { emoji: "🎖️", name: "military medal", category: "Activities" },
  { emoji: "🏵️", name: "rosette", category: "Activities" },
  { emoji: "🎗️", name: "reminder ribbon", category: "Activities" },
  { emoji: "🎫", name: "ticket", category: "Activities" },
  { emoji: "🎟️", name: "admission tickets", category: "Activities" },
  { emoji: "🎪", name: "circus tent", category: "Activities" },
  { emoji: "🤹", name: "juggling", category: "Activities" },
  { emoji: "🎭", name: "performing arts masks", category: "Activities" },
  { emoji: "🎨", name: "art palette painting", category: "Activities" },
  { emoji: "🎬", name: "clapper movie film", category: "Activities" },
  { emoji: "🎤", name: "microphone sing", category: "Activities" },
  { emoji: "🎧", name: "headphones", category: "Activities" },
  { emoji: "🎼", name: "musical score", category: "Activities" },
  { emoji: "🎵", name: "musical note", category: "Activities" },
  { emoji: "🎶", name: "musical notes music", category: "Activities" },
  { emoji: "🥁", name: "drum", category: "Activities" },
  { emoji: "🪘", name: "long drum", category: "Activities" },
  { emoji: "🎹", name: "piano keyboard", category: "Activities" },
  { emoji: "🎷", name: "saxophone", category: "Activities" },
  { emoji: "🎺", name: "trumpet", category: "Activities" },
  { emoji: "🎸", name: "guitar", category: "Activities" },
  { emoji: "🪕", name: "banjo", category: "Activities" },
  { emoji: "🎻", name: "violin", category: "Activities" },
  { emoji: "🎲", name: "dice game", category: "Activities" },
  { emoji: "♟️", name: "chess pawn", category: "Activities" },
  { emoji: "🎯", name: "darts bullseye target", category: "Activities" },
  { emoji: "🎳", name: "bowling", category: "Activities" },
  { emoji: "🎮", name: "video game controller", category: "Activities" },
  { emoji: "🕹️", name: "joystick", category: "Activities" },
  { emoji: "🎰", name: "slot machine", category: "Activities" },
  { emoji: "🧩", name: "puzzle piece", category: "Activities" },

  // ─────────────── Travel & Places ───────────────
  { emoji: "🚗", name: "car", category: "Travel" },
  { emoji: "🚕", name: "taxi", category: "Travel" },
  { emoji: "🚙", name: "suv", category: "Travel" },
  { emoji: "🚌", name: "bus", category: "Travel" },
  { emoji: "🚎", name: "trolleybus", category: "Travel" },
  { emoji: "🏎️", name: "race car", category: "Travel" },
  { emoji: "🚓", name: "police car", category: "Travel" },
  { emoji: "🚑", name: "ambulance", category: "Travel" },
  { emoji: "🚒", name: "fire engine", category: "Travel" },
  { emoji: "🚐", name: "minibus van", category: "Travel" },
  { emoji: "🛻", name: "pickup truck", category: "Travel" },
  { emoji: "🚚", name: "delivery truck", category: "Travel" },
  { emoji: "🚛", name: "articulated lorry", category: "Travel" },
  { emoji: "🚜", name: "tractor", category: "Travel" },
  { emoji: "🦽", name: "wheelchair manual", category: "Travel" },
  { emoji: "🛵", name: "scooter motor", category: "Travel" },
  { emoji: "🏍️", name: "motorcycle", category: "Travel" },
  { emoji: "🛺", name: "auto rickshaw", category: "Travel" },
  { emoji: "🚲", name: "bicycle bike", category: "Travel" },
  { emoji: "🛴", name: "kick scooter", category: "Travel" },
  { emoji: "🚨", name: "police light siren", category: "Travel" },
  { emoji: "🚍", name: "oncoming bus", category: "Travel" },
  { emoji: "🚔", name: "oncoming police", category: "Travel" },
  { emoji: "🚖", name: "oncoming taxi", category: "Travel" },
  { emoji: "🚇", name: "metro subway", category: "Travel" },
  { emoji: "🚊", name: "tram", category: "Travel" },
  { emoji: "🚉", name: "station", category: "Travel" },
  { emoji: "✈️", name: "airplane flight", category: "Travel" },
  { emoji: "🛫", name: "airplane departure takeoff", category: "Travel" },
  { emoji: "🛬", name: "airplane arrival landing", category: "Travel" },
  { emoji: "🛩️", name: "small airplane", category: "Travel" },
  { emoji: "💺", name: "seat", category: "Travel" },
  { emoji: "🚁", name: "helicopter", category: "Travel" },
  { emoji: "🚀", name: "rocket launch", category: "Travel" },
  { emoji: "🛸", name: "flying saucer ufo", category: "Travel" },
  { emoji: "🛰️", name: "satellite", category: "Travel" },
  { emoji: "⛵", name: "sailboat", category: "Travel" },
  { emoji: "🛶", name: "canoe", category: "Travel" },
  { emoji: "🚤", name: "speedboat", category: "Travel" },
  { emoji: "🛳️", name: "passenger ship", category: "Travel" },
  { emoji: "⛴️", name: "ferry", category: "Travel" },
  { emoji: "🚢", name: "ship", category: "Travel" },
  { emoji: "⚓", name: "anchor", category: "Travel" },
  { emoji: "⛽", name: "fuel gas pump", category: "Travel" },
  { emoji: "🚧", name: "construction barrier", category: "Travel" },
  { emoji: "🚦", name: "traffic light", category: "Travel" },
  { emoji: "🗺️", name: "world map", category: "Travel" },
  { emoji: "🗿", name: "moai statue", category: "Travel" },
  { emoji: "🗽", name: "statue of liberty", category: "Travel" },
  { emoji: "🗼", name: "tokyo tower", category: "Travel" },
  { emoji: "🏰", name: "castle", category: "Travel" },
  { emoji: "🏯", name: "japanese castle", category: "Travel" },
  { emoji: "🏟️", name: "stadium", category: "Travel" },
  { emoji: "🎡", name: "ferris wheel", category: "Travel" },
  { emoji: "🎢", name: "roller coaster", category: "Travel" },
  { emoji: "🎠", name: "carousel horse", category: "Travel" },
  { emoji: "⛲", name: "fountain", category: "Travel" },
  { emoji: "⛱️", name: "beach umbrella", category: "Travel" },
  { emoji: "🏖️", name: "beach", category: "Travel" },
  { emoji: "🏝️", name: "desert island", category: "Travel" },
  { emoji: "🏜️", name: "desert", category: "Travel" },
  { emoji: "🌋", name: "volcano", category: "Travel" },
  { emoji: "⛰️", name: "mountain", category: "Travel" },
  { emoji: "🏔️", name: "snowy mountain", category: "Travel" },
  { emoji: "🗻", name: "mount fuji", category: "Travel" },
  { emoji: "🏕️", name: "camping tent", category: "Travel" },
  { emoji: "⛺", name: "tent", category: "Travel" },
  { emoji: "🏠", name: "house home", category: "Travel" },
  { emoji: "🏡", name: "house garden", category: "Travel" },
  { emoji: "🏘️", name: "houses", category: "Travel" },
  { emoji: "🏢", name: "office building", category: "Travel" },
  { emoji: "🏬", name: "department store", category: "Travel" },
  { emoji: "🏭", name: "factory", category: "Travel" },
  { emoji: "🏥", name: "hospital", category: "Travel" },
  { emoji: "🏦", name: "bank", category: "Travel" },
  { emoji: "🏨", name: "hotel", category: "Travel" },
  { emoji: "🏪", name: "convenience store", category: "Travel" },
  { emoji: "🏫", name: "school", category: "Travel" },
  { emoji: "💒", name: "wedding chapel", category: "Travel" },
  { emoji: "⛪", name: "church", category: "Travel" },
  { emoji: "🕌", name: "mosque", category: "Travel" },
  { emoji: "🛕", name: "hindu temple", category: "Travel" },
  { emoji: "🕍", name: "synagogue", category: "Travel" },
  { emoji: "⛩️", name: "shinto shrine", category: "Travel" },
  { emoji: "🌁", name: "foggy", category: "Travel" },
  { emoji: "🌃", name: "night stars city", category: "Travel" },
  { emoji: "🏙️", name: "cityscape", category: "Travel" },
  { emoji: "🌆", name: "sunset city dusk", category: "Travel" },
  { emoji: "🌇", name: "sunset buildings", category: "Travel" },
  { emoji: "🌉", name: "bridge night", category: "Travel" },
  { emoji: "🌌", name: "milky way galaxy", category: "Travel" },
  { emoji: "🎇", name: "sparkler", category: "Travel" },
  { emoji: "🎆", name: "fireworks", category: "Travel" },

  // ─────────────── Objects ───────────────
  { emoji: "⌚", name: "watch", category: "Objects" },
  { emoji: "📱", name: "phone mobile", category: "Objects" },
  { emoji: "💻", name: "laptop computer", category: "Objects" },
  { emoji: "⌨️", name: "keyboard", category: "Objects" },
  { emoji: "🖥️", name: "desktop computer", category: "Objects" },
  { emoji: "🖨️", name: "printer", category: "Objects" },
  { emoji: "🖱️", name: "mouse computer", category: "Objects" },
  { emoji: "💽", name: "minidisc", category: "Objects" },
  { emoji: "💾", name: "floppy disk save", category: "Objects" },
  { emoji: "💿", name: "cd disc", category: "Objects" },
  { emoji: "📀", name: "dvd", category: "Objects" },
  { emoji: "📷", name: "camera", category: "Objects" },
  { emoji: "📸", name: "camera flash", category: "Objects" },
  { emoji: "📹", name: "video camera", category: "Objects" },
  { emoji: "🎥", name: "movie camera", category: "Objects" },
  { emoji: "📞", name: "telephone receiver", category: "Objects" },
  { emoji: "☎️", name: "telephone", category: "Objects" },
  { emoji: "📟", name: "pager", category: "Objects" },
  { emoji: "📺", name: "television tv", category: "Objects" },
  { emoji: "📻", name: "radio", category: "Objects" },
  { emoji: "🎙️", name: "studio microphone", category: "Objects" },
  { emoji: "⏰", name: "alarm clock", category: "Objects" },
  { emoji: "⏱️", name: "stopwatch", category: "Objects" },
  { emoji: "⌛", name: "hourglass done", category: "Objects" },
  { emoji: "⏳", name: "hourglass flowing", category: "Objects" },
  { emoji: "🔋", name: "battery", category: "Objects" },
  { emoji: "🔌", name: "plug electric", category: "Objects" },
  { emoji: "💡", name: "light bulb idea", category: "Objects" },
  { emoji: "🔦", name: "flashlight torch", category: "Objects" },
  { emoji: "🕯️", name: "candle", category: "Objects" },
  { emoji: "🪔", name: "diya lamp", category: "Objects" },
  { emoji: "🧯", name: "fire extinguisher", category: "Objects" },
  { emoji: "🛢️", name: "oil drum", category: "Objects" },
  { emoji: "💸", name: "money wings flying", category: "Objects" },
  { emoji: "💵", name: "dollar money", category: "Objects" },
  { emoji: "💴", name: "yen money", category: "Objects" },
  { emoji: "💶", name: "euro money", category: "Objects" },
  { emoji: "💷", name: "pound money", category: "Objects" },
  { emoji: "💰", name: "money bag", category: "Objects" },
  { emoji: "💳", name: "credit card", category: "Objects" },
  { emoji: "💎", name: "gem diamond", category: "Objects" },
  { emoji: "⚖️", name: "balance scale justice", category: "Objects" },
  { emoji: "🪜", name: "ladder", category: "Objects" },
  { emoji: "🧰", name: "toolbox", category: "Objects" },
  { emoji: "🔧", name: "wrench", category: "Objects" },
  { emoji: "🔨", name: "hammer", category: "Objects" },
  { emoji: "⚒️", name: "hammer and pick", category: "Objects" },
  { emoji: "🛠️", name: "hammer and wrench tools", category: "Objects" },
  { emoji: "⛏️", name: "pick axe", category: "Objects" },
  { emoji: "🔩", name: "nut and bolt", category: "Objects" },
  { emoji: "⚙️", name: "gear settings", category: "Objects" },
  { emoji: "🧱", name: "brick", category: "Objects" },
  { emoji: "⛓️", name: "chains", category: "Objects" },
  { emoji: "🧲", name: "magnet", category: "Objects" },
  { emoji: "🔫", name: "water pistol gun", category: "Objects" },
  { emoji: "💣", name: "bomb", category: "Objects" },
  { emoji: "🧨", name: "firecracker dynamite", category: "Objects" },
  { emoji: "🔪", name: "knife", category: "Objects" },
  { emoji: "🗡️", name: "dagger", category: "Objects" },
  { emoji: "⚔️", name: "crossed swords", category: "Objects" },
  { emoji: "🛡️", name: "shield", category: "Objects" },
  { emoji: "🚬", name: "cigarette", category: "Objects" },
  { emoji: "⚰️", name: "coffin", category: "Objects" },
  { emoji: "🪦", name: "headstone grave", category: "Objects" },
  { emoji: "🏺", name: "amphora vase", category: "Objects" },
  { emoji: "🔮", name: "crystal ball", category: "Objects" },
  { emoji: "🪬", name: "hamsa", category: "Objects" },
  { emoji: "🧿", name: "evil eye nazar", category: "Objects" },
  { emoji: "💈", name: "barber pole", category: "Objects" },
  { emoji: "🔭", name: "telescope", category: "Objects" },
  { emoji: "🔬", name: "microscope", category: "Objects" },
  { emoji: "🩺", name: "stethoscope", category: "Objects" },
  { emoji: "💊", name: "pill medicine", category: "Objects" },
  { emoji: "💉", name: "syringe injection", category: "Objects" },
  { emoji: "🩹", name: "bandage", category: "Objects" },
  { emoji: "🩼", name: "crutch", category: "Objects" },
  { emoji: "🌡️", name: "thermometer", category: "Objects" },
  { emoji: "🧬", name: "dna", category: "Objects" },
  { emoji: "🦠", name: "microbe germ virus", category: "Objects" },
  { emoji: "🧪", name: "test tube", category: "Objects" },
  { emoji: "🧫", name: "petri dish", category: "Objects" },
  { emoji: "🧹", name: "broom", category: "Objects" },
  { emoji: "🧺", name: "basket laundry", category: "Objects" },
  { emoji: "🧻", name: "toilet paper", category: "Objects" },
  { emoji: "🚽", name: "toilet", category: "Objects" },
  { emoji: "🚿", name: "shower", category: "Objects" },
  { emoji: "🛁", name: "bathtub", category: "Objects" },
  { emoji: "🧼", name: "soap", category: "Objects" },
  { emoji: "🪥", name: "toothbrush", category: "Objects" },
  { emoji: "🧽", name: "sponge", category: "Objects" },
  { emoji: "🔑", name: "key", category: "Objects" },
  { emoji: "🗝️", name: "old key", category: "Objects" },
  { emoji: "🔒", name: "locked", category: "Objects" },
  { emoji: "🔓", name: "unlocked", category: "Objects" },
  { emoji: "🔐", name: "locked with key", category: "Objects" },
  { emoji: "🚪", name: "door", category: "Objects" },
  { emoji: "🪑", name: "chair", category: "Objects" },
  { emoji: "🛋️", name: "couch sofa", category: "Objects" },
  { emoji: "🛏️", name: "bed", category: "Objects" },
  { emoji: "🧳", name: "luggage suitcase", category: "Objects" },
  { emoji: "🎁", name: "gift present", category: "Objects" },
  { emoji: "🎈", name: "balloon", category: "Objects" },
  { emoji: "🎀", name: "ribbon bow", category: "Objects" },
  { emoji: "🪄", name: "magic wand", category: "Objects" },
  { emoji: "🎏", name: "carp streamer", category: "Objects" },
  { emoji: "🎐", name: "wind chime", category: "Objects" },
  { emoji: "🧧", name: "red envelope", category: "Objects" },
  { emoji: "✉️", name: "envelope mail", category: "Objects" },
  { emoji: "📩", name: "envelope arrow", category: "Objects" },
  { emoji: "📨", name: "incoming envelope", category: "Objects" },
  { emoji: "📧", name: "email", category: "Objects" },
  { emoji: "💌", name: "love letter", category: "Objects" },
  { emoji: "📮", name: "postbox", category: "Objects" },
  { emoji: "📦", name: "package box", category: "Objects" },
  { emoji: "📫", name: "mailbox", category: "Objects" },
  { emoji: "📝", name: "memo note pencil", category: "Objects" },
  { emoji: "✏️", name: "pencil", category: "Objects" },
  { emoji: "✒️", name: "black nib pen", category: "Objects" },
  { emoji: "🖊️", name: "pen", category: "Objects" },
  { emoji: "🖍️", name: "crayon", category: "Objects" },
  { emoji: "🖌️", name: "paintbrush", category: "Objects" },
  { emoji: "📚", name: "books", category: "Objects" },
  { emoji: "📖", name: "open book", category: "Objects" },
  { emoji: "📕", name: "closed book", category: "Objects" },
  { emoji: "📗", name: "green book", category: "Objects" },
  { emoji: "📘", name: "blue book", category: "Objects" },
  { emoji: "📙", name: "orange book", category: "Objects" },
  { emoji: "📔", name: "notebook decorative", category: "Objects" },
  { emoji: "📒", name: "ledger", category: "Objects" },
  { emoji: "📓", name: "notebook", category: "Objects" },
  { emoji: "📃", name: "page curl", category: "Objects" },
  { emoji: "📄", name: "page document", category: "Objects" },
  { emoji: "📰", name: "newspaper", category: "Objects" },
  { emoji: "📑", name: "bookmark tabs", category: "Objects" },
  { emoji: "🔖", name: "bookmark", category: "Objects" },
  { emoji: "🏷️", name: "label tag", category: "Objects" },
  { emoji: "📌", name: "pushpin", category: "Objects" },
  { emoji: "📍", name: "round pin location", category: "Objects" },
  { emoji: "📎", name: "paperclip", category: "Objects" },
  { emoji: "📐", name: "triangular ruler", category: "Objects" },
  { emoji: "📏", name: "straight ruler", category: "Objects" },
  { emoji: "✂️", name: "scissors", category: "Objects" },
  { emoji: "🗃️", name: "card file box", category: "Objects" },
  { emoji: "🗄️", name: "file cabinet", category: "Objects" },
  { emoji: "🗂️", name: "card index dividers", category: "Objects" },
  { emoji: "📅", name: "calendar", category: "Objects" },
  { emoji: "📆", name: "tear off calendar", category: "Objects" },
  { emoji: "📇", name: "card index", category: "Objects" },
  { emoji: "📊", name: "bar chart", category: "Objects" },
  { emoji: "📈", name: "chart up trend", category: "Objects" },
  { emoji: "📉", name: "chart down", category: "Objects" },
  { emoji: "📋", name: "clipboard", category: "Objects" },
  { emoji: "🗒️", name: "spiral notepad", category: "Objects" },
  { emoji: "🗓️", name: "spiral calendar", category: "Objects" },
  { emoji: "📁", name: "folder", category: "Objects" },
  { emoji: "📂", name: "open folder", category: "Objects" },
  { emoji: "🗳️", name: "ballot box", category: "Objects" },
  { emoji: "🖇️", name: "linked paperclips", category: "Objects" },
  { emoji: "👓", name: "glasses", category: "Objects" },
  { emoji: "🕶️", name: "sunglasses", category: "Objects" },
  { emoji: "🥽", name: "goggles", category: "Objects" },
  { emoji: "🥼", name: "lab coat", category: "Objects" },
  { emoji: "🦺", name: "safety vest", category: "Objects" },
  { emoji: "👔", name: "necktie", category: "Objects" },
  { emoji: "👕", name: "t-shirt", category: "Objects" },
  { emoji: "👖", name: "jeans", category: "Objects" },
  { emoji: "🧣", name: "scarf", category: "Objects" },
  { emoji: "🧤", name: "gloves", category: "Objects" },
  { emoji: "🧥", name: "coat", category: "Objects" },
  { emoji: "🧦", name: "socks", category: "Objects" },
  { emoji: "👗", name: "dress", category: "Objects" },
  { emoji: "👘", name: "kimono", category: "Objects" },
  { emoji: "🥻", name: "sari", category: "Objects" },
  { emoji: "👙", name: "bikini", category: "Objects" },
  { emoji: "👚", name: "blouse", category: "Objects" },
  { emoji: "👛", name: "purse", category: "Objects" },
  { emoji: "👜", name: "handbag", category: "Objects" },
  { emoji: "👝", name: "clutch pouch", category: "Objects" },
  { emoji: "🎒", name: "backpack", category: "Objects" },
  { emoji: "👞", name: "mans shoe", category: "Objects" },
  { emoji: "👟", name: "sneaker running shoe", category: "Objects" },
  { emoji: "🥾", name: "hiking boot", category: "Objects" },
  { emoji: "🥿", name: "flat shoe", category: "Objects" },
  { emoji: "👠", name: "high heel", category: "Objects" },
  { emoji: "👡", name: "sandal", category: "Objects" },
  { emoji: "🩴", name: "flip flop thong", category: "Objects" },
  { emoji: "👢", name: "boot", category: "Objects" },
  { emoji: "👑", name: "crown", category: "Objects" },
  { emoji: "👒", name: "womans hat", category: "Objects" },
  { emoji: "🎩", name: "top hat", category: "Objects" },
  { emoji: "🎓", name: "graduation cap", category: "Objects" },
  { emoji: "🧢", name: "billed cap", category: "Objects" },
  { emoji: "⛑️", name: "rescue helmet", category: "Objects" },
  { emoji: "💄", name: "lipstick", category: "Objects" },
  { emoji: "💍", name: "ring", category: "Objects" },
  { emoji: "🌂", name: "closed umbrella", category: "Objects" },
  { emoji: "☂️", name: "umbrella", category: "Objects" },

  // ─────────────── Symbols ───────────────
  { emoji: "❤️", name: "red heart love", category: "Symbols" },
  { emoji: "🧡", name: "orange heart", category: "Symbols" },
  { emoji: "💛", name: "yellow heart", category: "Symbols" },
  { emoji: "💚", name: "green heart", category: "Symbols" },
  { emoji: "💙", name: "blue heart", category: "Symbols" },
  { emoji: "💜", name: "purple heart", category: "Symbols" },
  { emoji: "🖤", name: "black heart", category: "Symbols" },
  { emoji: "🤍", name: "white heart", category: "Symbols" },
  { emoji: "🤎", name: "brown heart", category: "Symbols" },
  { emoji: "💔", name: "broken heart", category: "Symbols" },
  { emoji: "❤️‍🔥", name: "heart on fire", category: "Symbols" },
  { emoji: "❤️‍🩹", name: "mending heart", category: "Symbols" },
  { emoji: "💕", name: "two hearts", category: "Symbols" },
  { emoji: "💞", name: "revolving hearts", category: "Symbols" },
  { emoji: "💓", name: "beating heart", category: "Symbols" },
  { emoji: "💗", name: "growing heart", category: "Symbols" },
  { emoji: "💖", name: "sparkling heart", category: "Symbols" },
  { emoji: "💘", name: "heart arrow cupid", category: "Symbols" },
  { emoji: "💝", name: "heart with ribbon gift", category: "Symbols" },
  { emoji: "💟", name: "heart decoration", category: "Symbols" },
  { emoji: "♥️", name: "heart suit", category: "Symbols" },
  { emoji: "💋", name: "kiss mark lips", category: "Symbols" },
  { emoji: "💯", name: "hundred points perfect", category: "Symbols" },
  { emoji: "💢", name: "anger symbol", category: "Symbols" },
  { emoji: "💥", name: "collision boom", category: "Symbols" },
  { emoji: "💫", name: "dizzy stars", category: "Symbols" },
  { emoji: "💦", name: "sweat droplets", category: "Symbols" },
  { emoji: "💨", name: "dash wind", category: "Symbols" },
  { emoji: "🕳️", name: "hole", category: "Symbols" },
  { emoji: "💬", name: "speech bubble", category: "Symbols" },
  { emoji: "💭", name: "thought bubble", category: "Symbols" },
  { emoji: "🗯️", name: "anger bubble", category: "Symbols" },
  { emoji: "♨️", name: "hot springs", category: "Symbols" },
  { emoji: "💤", name: "zzz sleep", category: "Symbols" },
  { emoji: "✨", name: "sparkles", category: "Symbols" },
  { emoji: "🌟", name: "glowing star", category: "Symbols" },
  { emoji: "⭐", name: "star", category: "Symbols" },
  { emoji: "🌠", name: "shooting star", category: "Symbols" },
  { emoji: "🔥", name: "fire lit", category: "Symbols" },
  { emoji: "⚡", name: "lightning high voltage", category: "Symbols" },
  { emoji: "☀️", name: "sun", category: "Symbols" },
  { emoji: "🌈", name: "rainbow", category: "Symbols" },
  { emoji: "☁️", name: "cloud", category: "Symbols" },
  { emoji: "⛅", name: "sun behind cloud", category: "Symbols" },
  { emoji: "🌧️", name: "rain cloud", category: "Symbols" },
  { emoji: "⛈️", name: "thunderstorm", category: "Symbols" },
  { emoji: "❄️", name: "snowflake", category: "Symbols" },
  { emoji: "☃️", name: "snowman", category: "Symbols" },
  { emoji: "⛄", name: "snowman no snow", category: "Symbols" },
  { emoji: "🌊", name: "wave ocean water", category: "Symbols" },
  { emoji: "💧", name: "droplet", category: "Symbols" },
  { emoji: "🌙", name: "crescent moon", category: "Symbols" },
  { emoji: "🌛", name: "first quarter moon face", category: "Symbols" },
  { emoji: "🌜", name: "last quarter moon face", category: "Symbols" },
  { emoji: "🌕", name: "full moon", category: "Symbols" },
  { emoji: "🌝", name: "full moon face", category: "Symbols" },
  { emoji: "🌞", name: "sun with face", category: "Symbols" },
  { emoji: "🪐", name: "ringed planet saturn", category: "Symbols" },
  { emoji: "🌍", name: "earth globe", category: "Symbols" },
  { emoji: "✅", name: "check mark green", category: "Symbols" },
  { emoji: "✔️", name: "check mark", category: "Symbols" },
  { emoji: "☑️", name: "check box", category: "Symbols" },
  { emoji: "❌", name: "cross mark x wrong", category: "Symbols" },
  { emoji: "❎", name: "cross mark button", category: "Symbols" },
  { emoji: "➕", name: "plus", category: "Symbols" },
  { emoji: "➖", name: "minus", category: "Symbols" },
  { emoji: "➗", name: "divide", category: "Symbols" },
  { emoji: "✖️", name: "multiply", category: "Symbols" },
  { emoji: "❓", name: "question mark", category: "Symbols" },
  { emoji: "❗", name: "exclamation", category: "Symbols" },
  { emoji: "❕", name: "white exclamation", category: "Symbols" },
  { emoji: "❔", name: "white question", category: "Symbols" },
  { emoji: "‼️", name: "double exclamation", category: "Symbols" },
  { emoji: "⁉️", name: "exclamation question", category: "Symbols" },
  { emoji: "💲", name: "dollar sign", category: "Symbols" },
  { emoji: "💱", name: "currency exchange", category: "Symbols" },
  { emoji: "™️", name: "trademark", category: "Symbols" },
  { emoji: "©️", name: "copyright", category: "Symbols" },
  { emoji: "®️", name: "registered", category: "Symbols" },
  { emoji: "〰️", name: "wavy dash", category: "Symbols" },
  { emoji: "➰", name: "curly loop", category: "Symbols" },
  { emoji: "➿", name: "double loop", category: "Symbols" },
  { emoji: "🔚", name: "end arrow", category: "Symbols" },
  { emoji: "🔙", name: "back arrow", category: "Symbols" },
  { emoji: "🔛", name: "on arrow", category: "Symbols" },
  { emoji: "🔝", name: "top arrow", category: "Symbols" },
  { emoji: "🔜", name: "soon arrow", category: "Symbols" },
  { emoji: "✳️", name: "eight spoked asterisk", category: "Symbols" },
  { emoji: "✴️", name: "eight pointed star", category: "Symbols" },
  { emoji: "❇️", name: "sparkle", category: "Symbols" },
  { emoji: "⚠️", name: "warning", category: "Symbols" },
  { emoji: "🚸", name: "children crossing", category: "Symbols" },
  { emoji: "🔱", name: "trident", category: "Symbols" },
  { emoji: "⚜️", name: "fleur de lis", category: "Symbols" },
  { emoji: "🔰", name: "beginner", category: "Symbols" },
  { emoji: "♻️", name: "recycle", category: "Symbols" },
  { emoji: "✅", name: "tick", category: "Symbols" },
  { emoji: "🆗", name: "ok button", category: "Symbols" },
  { emoji: "🆕", name: "new button", category: "Symbols" },
  { emoji: "🆒", name: "cool button", category: "Symbols" },
  { emoji: "🆓", name: "free button", category: "Symbols" },
  { emoji: "🆙", name: "up button", category: "Symbols" },
  { emoji: "🔟", name: "keycap ten", category: "Symbols" },
  { emoji: "🔢", name: "numbers input", category: "Symbols" },
  { emoji: "#️⃣", name: "hash keycap", category: "Symbols" },
  { emoji: "*️⃣", name: "asterisk keycap", category: "Symbols" },
  { emoji: "▶️", name: "play button", category: "Symbols" },
  { emoji: "⏸️", name: "pause button", category: "Symbols" },
  { emoji: "⏯️", name: "play pause", category: "Symbols" },
  { emoji: "⏹️", name: "stop button", category: "Symbols" },
  { emoji: "⏭️", name: "next track", category: "Symbols" },
  { emoji: "⏮️", name: "previous track", category: "Symbols" },
  { emoji: "🔀", name: "shuffle", category: "Symbols" },
  { emoji: "🔁", name: "repeat", category: "Symbols" },
  { emoji: "🔂", name: "repeat one", category: "Symbols" },
  { emoji: "🔼", name: "up button small", category: "Symbols" },
  { emoji: "🔽", name: "down button small", category: "Symbols" },
  { emoji: "⏏️", name: "eject", category: "Symbols" },
  { emoji: "🔊", name: "speaker loud", category: "Symbols" },
  { emoji: "🔉", name: "speaker medium", category: "Symbols" },
  { emoji: "🔈", name: "speaker low", category: "Symbols" },
  { emoji: "🔇", name: "muted speaker", category: "Symbols" },
  { emoji: "📢", name: "loudspeaker", category: "Symbols" },
  { emoji: "📣", name: "megaphone cheer", category: "Symbols" },
  { emoji: "🔔", name: "bell", category: "Symbols" },
  { emoji: "🔕", name: "bell off mute", category: "Symbols" },
  { emoji: "🎵", name: "music note single", category: "Symbols" },
  { emoji: "🎶", name: "music notes", category: "Symbols" },
  { emoji: "♾️", name: "infinity", category: "Symbols" },
  { emoji: "💠", name: "diamond dot", category: "Symbols" },
  { emoji: "🔘", name: "radio button", category: "Symbols" },
  { emoji: "🔴", name: "red circle", category: "Symbols" },
  { emoji: "🟠", name: "orange circle", category: "Symbols" },
  { emoji: "🟡", name: "yellow circle", category: "Symbols" },
  { emoji: "🟢", name: "green circle", category: "Symbols" },
  { emoji: "🔵", name: "blue circle", category: "Symbols" },
  { emoji: "🟣", name: "purple circle", category: "Symbols" },
  { emoji: "⚫", name: "black circle", category: "Symbols" },
  { emoji: "⚪", name: "white circle", category: "Symbols" },
  { emoji: "🟤", name: "brown circle", category: "Symbols" },
  { emoji: "🟥", name: "red square", category: "Symbols" },
  { emoji: "🟧", name: "orange square", category: "Symbols" },
  { emoji: "🟨", name: "yellow square", category: "Symbols" },
  { emoji: "🟩", name: "green square", category: "Symbols" },
  { emoji: "🟦", name: "blue square", category: "Symbols" },
  { emoji: "🟪", name: "purple square", category: "Symbols" },
  { emoji: "⬛", name: "black square", category: "Symbols" },
  { emoji: "⬜", name: "white square", category: "Symbols" },
  { emoji: "🟫", name: "brown square", category: "Symbols" },
  { emoji: "🔶", name: "large orange diamond", category: "Symbols" },
  { emoji: "🔷", name: "large blue diamond", category: "Symbols" },
  { emoji: "🔸", name: "small orange diamond", category: "Symbols" },
  { emoji: "🔹", name: "small blue diamond", category: "Symbols" },
  { emoji: "🔺", name: "red triangle up", category: "Symbols" },
  { emoji: "🔻", name: "red triangle down", category: "Symbols" },
  { emoji: "♠️", name: "spade suit", category: "Symbols" },
  { emoji: "♣️", name: "club suit", category: "Symbols" },
  { emoji: "♦️", name: "diamond suit", category: "Symbols" },
  { emoji: "🃏", name: "joker card", category: "Symbols" },
  { emoji: "🀄", name: "mahjong", category: "Symbols" },
  { emoji: "🎴", name: "flower cards", category: "Symbols" },
  { emoji: "🕉️", name: "om", category: "Symbols" },
  { emoji: "☮️", name: "peace symbol", category: "Symbols" },
  { emoji: "✝️", name: "latin cross", category: "Symbols" },
  { emoji: "☪️", name: "star and crescent", category: "Symbols" },
  { emoji: "🔯", name: "six pointed star", category: "Symbols" },
  { emoji: "☯️", name: "yin yang", category: "Symbols" },
  { emoji: "♈", name: "aries", category: "Symbols" },
  { emoji: "♉", name: "taurus", category: "Symbols" },
  { emoji: "♊", name: "gemini", category: "Symbols" },
  { emoji: "♋", name: "cancer zodiac", category: "Symbols" },
  { emoji: "♌", name: "leo", category: "Symbols" },
  { emoji: "♍", name: "virgo", category: "Symbols" },
  { emoji: "♎", name: "libra", category: "Symbols" },
  { emoji: "♏", name: "scorpio", category: "Symbols" },
  { emoji: "♐", name: "sagittarius", category: "Symbols" },
  { emoji: "♑", name: "capricorn", category: "Symbols" },
  { emoji: "♒", name: "aquarius", category: "Symbols" },
  { emoji: "♓", name: "pisces", category: "Symbols" },
  { emoji: "⛎", name: "ophiuchus", category: "Symbols" },
  { emoji: "🆔", name: "id button", category: "Symbols" },
  { emoji: "⚛️", name: "atom", category: "Symbols" },
  { emoji: "🉑", name: "acceptable button", category: "Symbols" },

  // ─────────────── Flags ───────────────
  { emoji: "🏁", name: "checkered flag finish", category: "Flags" },
  { emoji: "🚩", name: "triangular flag", category: "Flags" },
  { emoji: "🎌", name: "crossed flags", category: "Flags" },
  { emoji: "🏴", name: "black flag", category: "Flags" },
  { emoji: "🏳️", name: "white flag", category: "Flags" },
  { emoji: "🏳️‍🌈", name: "rainbow pride flag", category: "Flags" },
  { emoji: "🏳️‍⚧️", name: "transgender flag", category: "Flags" },
  { emoji: "🏴‍☠️", name: "pirate flag", category: "Flags" },
  { emoji: "🇺🇸", name: "united states usa flag", category: "Flags" },
  { emoji: "🇬🇧", name: "united kingdom uk flag", category: "Flags" },
  { emoji: "🇨🇦", name: "canada flag", category: "Flags" },
  { emoji: "🇮🇳", name: "india flag", category: "Flags" },
  { emoji: "🇦🇺", name: "australia flag", category: "Flags" },
  { emoji: "🇩🇪", name: "germany flag", category: "Flags" },
  { emoji: "🇫🇷", name: "france flag", category: "Flags" },
  { emoji: "🇮🇹", name: "italy flag", category: "Flags" },
  { emoji: "🇪🇸", name: "spain flag", category: "Flags" },
  { emoji: "🇵🇹", name: "portugal flag", category: "Flags" },
  { emoji: "🇧🇷", name: "brazil flag", category: "Flags" },
  { emoji: "🇲🇽", name: "mexico flag", category: "Flags" },
  { emoji: "🇯🇵", name: "japan flag", category: "Flags" },
  { emoji: "🇰🇷", name: "south korea flag", category: "Flags" },
  { emoji: "🇨🇳", name: "china flag", category: "Flags" },
  { emoji: "🇷🇺", name: "russia flag", category: "Flags" },
  { emoji: "🇳🇱", name: "netherlands flag", category: "Flags" },
  { emoji: "🇸🇪", name: "sweden flag", category: "Flags" },
  { emoji: "🇳🇴", name: "norway flag", category: "Flags" },
  { emoji: "🇩🇰", name: "denmark flag", category: "Flags" },
  { emoji: "🇫🇮", name: "finland flag", category: "Flags" },
  { emoji: "🇵🇱", name: "poland flag", category: "Flags" },
  { emoji: "🇮🇪", name: "ireland flag", category: "Flags" },
  { emoji: "🇨🇭", name: "switzerland flag", category: "Flags" },
  { emoji: "🇦🇹", name: "austria flag", category: "Flags" },
  { emoji: "🇧🇪", name: "belgium flag", category: "Flags" },
  { emoji: "🇬🇷", name: "greece flag", category: "Flags" },
  { emoji: "🇹🇷", name: "turkey flag", category: "Flags" },
  { emoji: "🇸🇦", name: "saudi arabia flag", category: "Flags" },
  { emoji: "🇦🇪", name: "uae emirates flag", category: "Flags" },
  { emoji: "🇮🇱", name: "israel flag", category: "Flags" },
  { emoji: "🇪🇬", name: "egypt flag", category: "Flags" },
  { emoji: "🇿🇦", name: "south africa flag", category: "Flags" },
  { emoji: "🇳🇬", name: "nigeria flag", category: "Flags" },
  { emoji: "🇰🇪", name: "kenya flag", category: "Flags" },
  { emoji: "🇵🇰", name: "pakistan flag", category: "Flags" },
  { emoji: "🇧🇩", name: "bangladesh flag", category: "Flags" },
  { emoji: "🇱🇰", name: "sri lanka flag", category: "Flags" },
  { emoji: "🇳🇵", name: "nepal flag", category: "Flags" },
  { emoji: "🇹🇭", name: "thailand flag", category: "Flags" },
  { emoji: "🇻🇳", name: "vietnam flag", category: "Flags" },
  { emoji: "🇵🇭", name: "philippines flag", category: "Flags" },
  { emoji: "🇮🇩", name: "indonesia flag", category: "Flags" },
  { emoji: "🇲🇾", name: "malaysia flag", category: "Flags" },
  { emoji: "🇸🇬", name: "singapore flag", category: "Flags" },
  { emoji: "🇦🇷", name: "argentina flag", category: "Flags" },
  { emoji: "🇨🇱", name: "chile flag", category: "Flags" },
  { emoji: "🇨🇴", name: "colombia flag", category: "Flags" },
  { emoji: "🇵🇪", name: "peru flag", category: "Flags" },
  { emoji: "🇺🇦", name: "ukraine flag", category: "Flags" },
];
