export interface EmojiItem {
  emoji: string;
  name: string;
  category: string;
}

export const EMOJI_CATEGORIES = [
  "Smileys",
  "People",
  "Animals",
  "Food",
  "Activities",
  "Travel",
  "Objects",
  "Symbols",
] as const;

export const QUICK_REACTIONS = ["❤️", "😂", "😮", "😢", "😡", "👍"];

export const EMOJI_DATA: EmojiItem[] = [
  // Smileys
  { emoji: "😀", name: "grinning", category: "Smileys" },
  { emoji: "😃", name: "smiley", category: "Smileys" },
  { emoji: "😄", name: "smile", category: "Smileys" },
  { emoji: "😁", name: "grin", category: "Smileys" },
  { emoji: "😆", name: "laughing", category: "Smileys" },
  { emoji: "😅", name: "sweat smile", category: "Smileys" },
  { emoji: "🤣", name: "rofl", category: "Smileys" },
  { emoji: "😂", name: "joy", category: "Smileys" },
  { emoji: "🙂", name: "slightly smiling", category: "Smileys" },
  { emoji: "😊", name: "blush", category: "Smileys" },
  { emoji: "😇", name: "innocent", category: "Smileys" },
  { emoji: "🥰", name: "smiling hearts", category: "Smileys" },
  { emoji: "😍", name: "heart eyes", category: "Smileys" },
  { emoji: "🤩", name: "star struck", category: "Smileys" },
  { emoji: "😘", name: "kissing heart", category: "Smileys" },
  { emoji: "😗", name: "kissing", category: "Smileys" },
  { emoji: "😚", name: "kissing closed eyes", category: "Smileys" },
  { emoji: "😙", name: "kissing smiling eyes", category: "Smileys" },
  { emoji: "🥲", name: "smiling tear", category: "Smileys" },
  { emoji: "😋", name: "yum", category: "Smileys" },
  { emoji: "😛", name: "stuck out tongue", category: "Smileys" },
  { emoji: "😜", name: "stuck out tongue winking", category: "Smileys" },
  { emoji: "🤪", name: "zany", category: "Smileys" },
  { emoji: "😝", name: "stuck out tongue closed eyes", category: "Smileys" },
  { emoji: "🤑", name: "money mouth", category: "Smileys" },
  { emoji: "🤗", name: "hugging", category: "Smileys" },
  { emoji: "🤭", name: "hand over mouth", category: "Smileys" },
  { emoji: "🤫", name: "shushing", category: "Smileys" },
  { emoji: "🤔", name: "thinking", category: "Smileys" },
  { emoji: "😐", name: "neutral", category: "Smileys" },
  { emoji: "😑", name: "expressionless", category: "Smileys" },
  { emoji: "😶", name: "no mouth", category: "Smileys" },
  { emoji: "😏", name: "smirk", category: "Smileys" },
  { emoji: "😒", name: "unamused", category: "Smileys" },
  { emoji: "🙄", name: "rolling eyes", category: "Smileys" },
  { emoji: "😬", name: "grimacing", category: "Smileys" },
  { emoji: "🤥", name: "lying", category: "Smileys" },
  { emoji: "😌", name: "relieved", category: "Smileys" },
  { emoji: "😔", name: "pensive", category: "Smileys" },
  { emoji: "😪", name: "sleepy", category: "Smileys" },
  { emoji: "🤤", name: "drooling", category: "Smileys" },
  { emoji: "😴", name: "sleeping", category: "Smileys" },
  { emoji: "😷", name: "mask", category: "Smileys" },
  { emoji: "🤒", name: "sick", category: "Smileys" },
  { emoji: "🤕", name: "injured", category: "Smileys" },
  { emoji: "🤢", name: "nauseated", category: "Smileys" },
  { emoji: "🤮", name: "vomiting", category: "Smileys" },
  { emoji: "🥵", name: "hot", category: "Smileys" },
  { emoji: "🥶", name: "cold", category: "Smileys" },
  { emoji: "😵", name: "dizzy", category: "Smileys" },
  { emoji: "🤯", name: "exploding head", category: "Smileys" },
  { emoji: "🥳", name: "partying", category: "Smileys" },
  { emoji: "🥺", name: "pleading", category: "Smileys" },
  { emoji: "😢", name: "cry", category: "Smileys" },
  { emoji: "😭", name: "sob", category: "Smileys" },
  { emoji: "😤", name: "triumph", category: "Smileys" },
  { emoji: "😠", name: "angry", category: "Smileys" },
  { emoji: "😡", name: "rage", category: "Smileys" },
  { emoji: "🤬", name: "cursing", category: "Smileys" },
  { emoji: "👿", name: "imp", category: "Smileys" },
  { emoji: "💀", name: "skull", category: "Smileys" },
  { emoji: "💩", name: "poop", category: "Smileys" },
  { emoji: "🤡", name: "clown", category: "Smileys" },
  { emoji: "👻", name: "ghost", category: "Smileys" },
  { emoji: "👽", name: "alien", category: "Smileys" },
  // People
  { emoji: "👋", name: "wave", category: "People" },
  { emoji: "🤚", name: "raised back of hand", category: "People" },
  { emoji: "✋", name: "raised hand", category: "People" },
  { emoji: "🖖", name: "vulcan salute", category: "People" },
  { emoji: "👌", name: "ok hand", category: "People" },
  { emoji: "🤌", name: "pinched fingers", category: "People" },
  { emoji: "✌️", name: "peace", category: "People" },
  { emoji: "🤞", name: "crossed fingers", category: "People" },
  { emoji: "🤟", name: "love you", category: "People" },
  { emoji: "🤘", name: "rock on", category: "People" },
  { emoji: "🤙", name: "call me", category: "People" },
  { emoji: "👈", name: "point left", category: "People" },
  { emoji: "👉", name: "point right", category: "People" },
  { emoji: "👆", name: "point up", category: "People" },
  { emoji: "👇", name: "point down", category: "People" },
  { emoji: "👍", name: "thumbs up", category: "People" },
  { emoji: "👎", name: "thumbs down", category: "People" },
  { emoji: "✊", name: "fist", category: "People" },
  { emoji: "👊", name: "punch", category: "People" },
  { emoji: "🤛", name: "left fist", category: "People" },
  { emoji: "🤜", name: "right fist", category: "People" },
  { emoji: "👏", name: "clap", category: "People" },
  { emoji: "🙌", name: "raised hands", category: "People" },
  { emoji: "👐", name: "open hands", category: "People" },
  { emoji: "🤲", name: "palms up", category: "People" },
  { emoji: "🤝", name: "handshake", category: "People" },
  { emoji: "🙏", name: "pray", category: "People" },
  { emoji: "💪", name: "muscle", category: "People" },
  { emoji: "🦾", name: "mechanical arm", category: "People" },
  { emoji: "💅", name: "nail polish", category: "People" },
  { emoji: "🤳", name: "selfie", category: "People" },
  // Animals
  { emoji: "🐶", name: "dog", category: "Animals" },
  { emoji: "🐱", name: "cat", category: "Animals" },
  { emoji: "🐭", name: "mouse", category: "Animals" },
  { emoji: "🐹", name: "hamster", category: "Animals" },
  { emoji: "🐰", name: "rabbit", category: "Animals" },
  { emoji: "🦊", name: "fox", category: "Animals" },
  { emoji: "🐻", name: "bear", category: "Animals" },
  { emoji: "🐼", name: "panda", category: "Animals" },
  { emoji: "🐨", name: "koala", category: "Animals" },
  { emoji: "🐯", name: "tiger", category: "Animals" },
  { emoji: "🦁", name: "lion", category: "Animals" },
  { emoji: "🐮", name: "cow", category: "Animals" },
  { emoji: "🐷", name: "pig", category: "Animals" },
  { emoji: "🐸", name: "frog", category: "Animals" },
  { emoji: "🐵", name: "monkey", category: "Animals" },
  { emoji: "🐔", name: "chicken", category: "Animals" },
  { emoji: "🐧", name: "penguin", category: "Animals" },
  { emoji: "🐦", name: "bird", category: "Animals" },
  { emoji: "🦋", name: "butterfly", category: "Animals" },
  { emoji: "🐛", name: "bug", category: "Animals" },
  { emoji: "🐝", name: "bee", category: "Animals" },
  { emoji: "🐞", name: "ladybug", category: "Animals" },
  { emoji: "🦄", name: "unicorn", category: "Animals" },
  { emoji: "🐍", name: "snake", category: "Animals" },
  { emoji: "🐢", name: "turtle", category: "Animals" },
  { emoji: "🐠", name: "tropical fish", category: "Animals" },
  { emoji: "🐬", name: "dolphin", category: "Animals" },
  { emoji: "🐳", name: "whale", category: "Animals" },
  // Food
  { emoji: "🍎", name: "apple", category: "Food" },
  { emoji: "🍐", name: "pear", category: "Food" },
  { emoji: "🍊", name: "orange", category: "Food" },
  { emoji: "🍋", name: "lemon", category: "Food" },
  { emoji: "🍌", name: "banana", category: "Food" },
  { emoji: "🍉", name: "watermelon", category: "Food" },
  { emoji: "🍇", name: "grapes", category: "Food" },
  { emoji: "🍓", name: "strawberry", category: "Food" },
  { emoji: "🫐", name: "blueberries", category: "Food" },
  { emoji: "🍕", name: "pizza", category: "Food" },
  { emoji: "🍔", name: "hamburger", category: "Food" },
  { emoji: "🍟", name: "fries", category: "Food" },
  { emoji: "🌭", name: "hot dog", category: "Food" },
  { emoji: "🍿", name: "popcorn", category: "Food" },
  { emoji: "🍩", name: "donut", category: "Food" },
  { emoji: "🍪", name: "cookie", category: "Food" },
  { emoji: "🎂", name: "birthday cake", category: "Food" },
  { emoji: "🍰", name: "cake", category: "Food" },
  { emoji: "🧁", name: "cupcake", category: "Food" },
  { emoji: "🍫", name: "chocolate", category: "Food" },
  { emoji: "🍬", name: "candy", category: "Food" },
  { emoji: "☕", name: "coffee", category: "Food" },
  { emoji: "🍵", name: "tea", category: "Food" },
  { emoji: "🧃", name: "juice box", category: "Food" },
  // Activities
  { emoji: "⚽", name: "soccer", category: "Activities" },
  { emoji: "🏀", name: "basketball", category: "Activities" },
  { emoji: "🏈", name: "football", category: "Activities" },
  { emoji: "⚾", name: "baseball", category: "Activities" },
  { emoji: "🎾", name: "tennis", category: "Activities" },
  { emoji: "🏐", name: "volleyball", category: "Activities" },
  { emoji: "🎮", name: "video game", category: "Activities" },
  { emoji: "🎯", name: "target", category: "Activities" },
  { emoji: "🎲", name: "dice", category: "Activities" },
  { emoji: "🎭", name: "performing arts", category: "Activities" },
  { emoji: "🎨", name: "art", category: "Activities" },
  { emoji: "🎬", name: "clapper board", category: "Activities" },
  { emoji: "🎤", name: "microphone", category: "Activities" },
  { emoji: "🎧", name: "headphones", category: "Activities" },
  { emoji: "🎵", name: "musical note", category: "Activities" },
  { emoji: "🎶", name: "musical notes", category: "Activities" },
  { emoji: "🏆", name: "trophy", category: "Activities" },
  { emoji: "🥇", name: "gold medal", category: "Activities" },
  // Travel
  { emoji: "🚗", name: "car", category: "Travel" },
  { emoji: "🚕", name: "taxi", category: "Travel" },
  { emoji: "🚌", name: "bus", category: "Travel" },
  { emoji: "✈️", name: "airplane", category: "Travel" },
  { emoji: "🚀", name: "rocket", category: "Travel" },
  { emoji: "🏠", name: "house", category: "Travel" },
  { emoji: "🏖️", name: "beach", category: "Travel" },
  { emoji: "🏔️", name: "mountain", category: "Travel" },
  { emoji: "🌍", name: "earth", category: "Travel" },
  { emoji: "🌙", name: "moon", category: "Travel" },
  { emoji: "⭐", name: "star", category: "Travel" },
  { emoji: "🌈", name: "rainbow", category: "Travel" },
  { emoji: "☀️", name: "sun", category: "Travel" },
  { emoji: "🌤️", name: "partly sunny", category: "Travel" },
  { emoji: "⛈️", name: "storm", category: "Travel" },
  { emoji: "❄️", name: "snowflake", category: "Travel" },
  // Objects
  { emoji: "📱", name: "phone", category: "Objects" },
  { emoji: "💻", name: "laptop", category: "Objects" },
  { emoji: "⌨️", name: "keyboard", category: "Objects" },
  { emoji: "📷", name: "camera", category: "Objects" },
  { emoji: "📹", name: "video camera", category: "Objects" },
  { emoji: "🔑", name: "key", category: "Objects" },
  { emoji: "💡", name: "light bulb", category: "Objects" },
  { emoji: "📚", name: "books", category: "Objects" },
  { emoji: "📝", name: "memo", category: "Objects" },
  { emoji: "📌", name: "pin", category: "Objects" },
  { emoji: "📎", name: "paperclip", category: "Objects" },
  { emoji: "✂️", name: "scissors", category: "Objects" },
  { emoji: "🔒", name: "lock", category: "Objects" },
  { emoji: "💎", name: "gem", category: "Objects" },
  { emoji: "🎁", name: "gift", category: "Objects" },
  { emoji: "🎈", name: "balloon", category: "Objects" },
  { emoji: "🎀", name: "ribbon", category: "Objects" },
  // Symbols
  { emoji: "❤️", name: "red heart", category: "Symbols" },
  { emoji: "🧡", name: "orange heart", category: "Symbols" },
  { emoji: "💛", name: "yellow heart", category: "Symbols" },
  { emoji: "💚", name: "green heart", category: "Symbols" },
  { emoji: "💙", name: "blue heart", category: "Symbols" },
  { emoji: "💜", name: "purple heart", category: "Symbols" },
  { emoji: "🖤", name: "black heart", category: "Symbols" },
  { emoji: "🤍", name: "white heart", category: "Symbols" },
  { emoji: "🤎", name: "brown heart", category: "Symbols" },
  { emoji: "💔", name: "broken heart", category: "Symbols" },
  { emoji: "💕", name: "two hearts", category: "Symbols" },
  { emoji: "💞", name: "revolving hearts", category: "Symbols" },
  { emoji: "💓", name: "heartbeat", category: "Symbols" },
  { emoji: "💗", name: "growing heart", category: "Symbols" },
  { emoji: "💖", name: "sparkling heart", category: "Symbols" },
  { emoji: "💘", name: "cupid", category: "Symbols" },
  { emoji: "💝", name: "heart with ribbon", category: "Symbols" },
  { emoji: "💟", name: "heart decoration", category: "Symbols" },
  { emoji: "✨", name: "sparkles", category: "Symbols" },
  { emoji: "💫", name: "dizzy", category: "Symbols" },
  { emoji: "🔥", name: "fire", category: "Symbols" },
  { emoji: "💯", name: "hundred", category: "Symbols" },
  { emoji: "✅", name: "check mark", category: "Symbols" },
  { emoji: "❌", name: "cross mark", category: "Symbols" },
  { emoji: "⚡", name: "lightning", category: "Symbols" },
  { emoji: "💤", name: "zzz", category: "Symbols" },
  { emoji: "🎉", name: "party", category: "Symbols" },
  { emoji: "🎊", name: "confetti", category: "Symbols" },
];
