-- Phase 5 — memory 2.0.
-- ============================================================================
-- The twin already had `ai_memories` (Phase 5 of the old build): a flat list of
-- facts, written by hand or by one greedy LLM call that read 80 messages.
--
-- This migration turns that into a memory that behaves:
--
--   1. `ai_memories` grows the columns a memory needs — pinned, importance,
--      seen_count / last_seen_at (so a fact that keeps coming back rises),
--      archived, the day it came from and the message it came from.
--   2. `message_highlights` — the lines worth keeping from their own chat
--      (promises, plans, dates, firsts, feelings). Chosen by free heuristics in
--      the app, stored here, readable by both partners, writable only by the
--      service role.
--   3. `twin_nightly_runs` — an audit row per sweep, so the UI can say when the
--      memory was last fed and how much it cost.
--   4. RPCs: `twin_memory_upsert` (the single writer, dedupes), pin / forget,
--      a trigram `twin_memory_search` for prompts and the UI, stats, and the
--      material a nightly sweep needs (`twin_day_messages`, service-role only).
--
-- Idempotent: `add column if not exists`, `create table if not exists`,
-- `create or replace`. Nothing is dropped, `messages` is never written.
--
-- Cost: everything in this file is free. The only AI in Phase 5 is the nightly
-- sweep, which spends at most one `extract` call per run on the top ~5% of the
-- day's lines (see `twin-nightly`).

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ── 1. ai_memories: the columns a memory needs ───────────────────────────
ALTER TABLE public.ai_memories ADD COLUMN IF NOT EXISTS pinned boolean NOT NULL DEFAULT false;
ALTER TABLE public.ai_memories ADD COLUMN IF NOT EXISTS archived boolean NOT NULL DEFAULT false;
ALTER TABLE public.ai_memories ADD COLUMN IF NOT EXISTS importance real NOT NULL DEFAULT 0.5;
ALTER TABLE public.ai_memories ADD COLUMN IF NOT EXISTS seen_count integer NOT NULL DEFAULT 1;
ALTER TABLE public.ai_memories ADD COLUMN IF NOT EXISTS last_seen_at timestamptz;
ALTER TABLE public.ai_memories ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.ai_memories ADD COLUMN IF NOT EXISTS day date;
ALTER TABLE public.ai_memories ADD COLUMN IF NOT EXISTS message_id uuid;
ALTER TABLE public.ai_memories ADD COLUMN IF NOT EXISTS kind text;

CREATE INDEX IF NOT EXISTS idx_ai_memories_rank
  ON public.ai_memories (subject_user_id, pinned DESC, importance DESC, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_memories_day
  ON public.ai_memories (day DESC) WHERE day IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ai_memories_fact_trgm
  ON public.ai_memories USING gin (lower(fact) gin_trgm_ops);

-- ── 2. message_highlights: the lines worth keeping ───────────────────────
CREATE TABLE IF NOT EXISTS public.message_highlights (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id  uuid REFERENCES public.messages(id) ON DELETE SET NULL,
  user_id     uuid,                          -- who said it (their real author)
  day         date NOT NULL,
  kind        text NOT NULL DEFAULT 'other', -- promise|plan|date|feeling|first|gift|place|milestone|other
  text        text NOT NULL,
  score       real NOT NULL DEFAULT 0.5,
  source      text NOT NULL DEFAULT 'heuristic', -- heuristic|llm
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- One row per (kind, line): a sweep can be re-run as often as you like.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_message_highlights
  ON public.message_highlights (kind, md5(lower(text)));
CREATE INDEX IF NOT EXISTS idx_message_highlights_day
  ON public.message_highlights (day DESC, score DESC);

-- Both partners may read what the twin noticed; only the service role writes.
ALTER TABLE public.message_highlights ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "partners read highlights" ON public.message_highlights;
CREATE POLICY "partners read highlights" ON public.message_highlights
  FOR SELECT TO authenticated
  USING (public.is_partner(auth.uid()));
REVOKE ALL ON TABLE public.message_highlights FROM anon;
GRANT SELECT ON TABLE public.message_highlights TO authenticated;
GRANT ALL ON TABLE public.message_highlights TO service_role;

-- ── 3. twin_nightly_runs: what the sweeps cost ───────────────────────────
CREATE TABLE IF NOT EXISTS public.twin_nightly_runs (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ran_at           timestamptz NOT NULL DEFAULT now(),
  days             integer NOT NULL DEFAULT 7,
  highlights       integer NOT NULL DEFAULT 0,
  facts_heuristic  integer NOT NULL DEFAULT 0,
  facts_llm        integer NOT NULL DEFAULT 0,
  llm_calls        integer NOT NULL DEFAULT 0,
  tokens           integer NOT NULL DEFAULT 0,
  note             text
);

ALTER TABLE public.twin_nightly_runs ENABLE ROW LEVEL SECURITY;
-- No policies on purpose: derived/private, service role only (hard rule #3).
REVOKE ALL ON TABLE public.twin_nightly_runs FROM anon, authenticated;
GRANT ALL ON TABLE public.twin_nightly_runs TO service_role;

-- ── 4. The single writer for a fact ──────────────────────────────────────
-- Dedupes on the existing unique (subject_user_id, lower(fact)) index and keeps
-- the strongest version: it never overwrites a manual fact with an auto one,
-- never loses a pin, and counts how often the fact keeps showing up.
CREATE OR REPLACE FUNCTION public.twin_memory_upsert(
  p_subject uuid,
  p_fact text,
  p_category text DEFAULT 'other',
  p_source text DEFAULT 'auto',
  p_confidence real DEFAULT 0.6,
  p_importance real DEFAULT 0.5,
  p_day date DEFAULT NULL,
  p_message_id uuid DEFAULT NULL,
  p_kind text DEFAULT NULL,
  p_owner uuid DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  clean text := left(btrim(regexp_replace(coalesce(p_fact, ''), '\s+', ' ', 'g')), 200);
  cat text := CASE WHEN p_category IN ('likes','dislikes','important','date','other') THEN p_category ELSE 'other' END;
  src text := CASE WHEN p_source = 'manual' THEN 'manual' ELSE 'auto' END;
  existing public.ai_memories%ROWTYPE;
  saved public.ai_memories%ROWTYPE;
BEGIN
  IF clean = '' OR length(clean) < 4 THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'too_short');
  END IF;

  SELECT * INTO existing
  FROM public.ai_memories
  WHERE subject_user_id = p_subject AND lower(fact) = lower(clean)
  LIMIT 1;

  IF FOUND THEN
    UPDATE public.ai_memories SET
      seen_count   = seen_count + 1,
      last_seen_at = now(),
      updated_at   = now(),
      -- a human edit wins; auto may only raise importance, never lower it
      importance   = greatest(importance, coalesce(p_importance, importance)),
      confidence   = greatest(confidence, coalesce(p_confidence, confidence)),
      source       = CASE WHEN source = 'manual' THEN 'manual' ELSE src END,
      day          = coalesce(day, p_day),
      message_id   = coalesce(message_id, p_message_id),
      kind         = coalesce(kind, p_kind)
    WHERE id = existing.id
    RETURNING * INTO saved;

    RETURN jsonb_build_object('ok', true, 'action', 'seen', 'id', saved.id, 'seen_count', saved.seen_count);
  END IF;

  INSERT INTO public.ai_memories (
    owner_user_id, subject_user_id, fact, category, source, confidence,
    importance, day, message_id, kind, seen_count, last_seen_at
  ) VALUES (
    coalesce(p_owner, p_subject), p_subject, clean, cat, src, coalesce(p_confidence, 0.6),
    coalesce(p_importance, 0.5), p_day, p_message_id, p_kind, 1, now()
  )
  RETURNING * INTO saved;

  RETURN jsonb_build_object('ok', true, 'action', 'inserted', 'id', saved.id);
END;
$$;
REVOKE ALL ON FUNCTION public.twin_memory_upsert(uuid, text, text, text, real, real, date, uuid, text, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.twin_memory_upsert(uuid, text, text, text, real, real, date, uuid, text, uuid) TO service_role;

-- ── 5. pin / forget: either partner, never the AI alone ──────────────────
CREATE OR REPLACE FUNCTION public.twin_memory_pin(p_id uuid, p_pinned boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  touched int;
BEGIN
  IF NOT public.is_partner(auth.uid()) THEN RAISE EXCEPTION 'Not a participant'; END IF;

  UPDATE public.ai_memories
     SET pinned = coalesce(p_pinned, true),
         importance = CASE WHEN coalesce(p_pinned, true) THEN 1.0 ELSE importance END,
         updated_at = now()
   WHERE id = p_id;
  GET DIAGNOSTICS touched = ROW_COUNT;

  RETURN jsonb_build_object('ok', touched > 0, 'pinned', coalesce(p_pinned, true));
END;
$$;
REVOKE ALL ON FUNCTION public.twin_memory_pin(uuid, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.twin_memory_pin(uuid, boolean) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.twin_memory_forget(p_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  touched int;
BEGIN
  IF NOT public.is_partner(auth.uid()) THEN RAISE EXCEPTION 'Not a participant'; END IF;

  DELETE FROM public.ai_memories WHERE id = p_id;
  GET DIAGNOSTICS touched = ROW_COUNT;

  RETURN jsonb_build_object('ok', touched > 0, 'forgotten', touched);
END;
$$;
REVOKE ALL ON FUNCTION public.twin_memory_forget(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.twin_memory_forget(uuid) TO authenticated, service_role;

-- ── 6. search: what the twin should remember right now ───────────────────
-- Trigram-first, so it works with no embeddings at all. Pinned facts always
-- come first, then the closest match, then importance. `p_query` may be NULL
-- (then it is simply "the most important things").
CREATE OR REPLACE FUNCTION public.twin_memory_search(
  p_query text DEFAULT NULL,
  p_subject uuid DEFAULT NULL,
  p_limit integer DEFAULT 8
)
RETURNS TABLE (
  id uuid, fact text, category text, source text,
  confidence real, importance real, pinned boolean, sim real, day date
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH q AS (SELECT nullif(btrim(coalesce(p_query, '')), '') AS t)
  SELECT m.id, m.fact, m.category, m.source, m.confidence, m.importance, m.pinned,
         CASE
           WHEN (SELECT t FROM q) IS NULL THEN 0::real
           ELSE greatest(similarity(m.fact, (SELECT t FROM q)),
                         word_similarity((SELECT t FROM q), m.fact))::real
         END AS sim,
         m.day
  FROM public.ai_memories m
  WHERE NOT m.archived
    AND (p_subject IS NULL OR m.subject_user_id = p_subject)
    AND (
      (SELECT t FROM q) IS NULL
      OR m.fact % (SELECT t FROM q)
      OR word_similarity((SELECT t FROM q), m.fact) > 0.2
      OR m.pinned
    )
  ORDER BY m.pinned DESC, sim DESC, m.importance DESC, m.updated_at DESC
  LIMIT greatest(coalesce(p_limit, 8), 1);
$$;
REVOKE ALL ON FUNCTION public.twin_memory_search(text, uuid, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.twin_memory_search(text, uuid, integer) TO authenticated, service_role;

-- ── 7. stats, for the control room ──────────────────────────────────────
CREATE OR REPLACE FUNCTION public.twin_memory_stats()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'total',        (SELECT count(*) FROM public.ai_memories WHERE NOT archived),
    'pinned',       (SELECT count(*) FROM public.ai_memories WHERE pinned AND NOT archived),
    'manual',       (SELECT count(*) FROM public.ai_memories WHERE source = 'manual' AND NOT archived),
    'auto',         (SELECT count(*) FROM public.ai_memories WHERE source = 'auto' AND NOT archived),
    'highlights',   (SELECT count(*) FROM public.message_highlights),
    'highlights_7d',(SELECT count(*) FROM public.message_highlights WHERE day > current_date - 7),
    'last_run',     (SELECT to_jsonb(r) FROM public.twin_nightly_runs r ORDER BY ran_at DESC LIMIT 1)
  )
  WHERE public.is_partner(auth.uid());
$$;
REVOKE ALL ON FUNCTION public.twin_memory_stats() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.twin_memory_stats() TO authenticated, service_role;

-- ── 8. The material a sweep needs ───────────────────────────────────────
-- One day of real lines, mechanical rows and placeholders already removed.
-- Service role only: this is raw chat, the app reads its own copy through RLS.
CREATE OR REPLACE FUNCTION public.twin_day_messages(p_day date)
RETURNS TABLE (
  id uuid, user_id uuid, username text, content text, message_type text, created_at timestamptz
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT m.id, m.user_id, m.username, m.content, m.message_type, m.created_at
  FROM public.messages m
  WHERE (m.created_at AT TIME ZONE 'Asia/Kolkata')::date = p_day
    AND NOT public.twin_is_ignored_message(m.message_type)
    AND NOT public.twin_is_placeholder_content(m.content)
  ORDER BY m.created_at ASC;
$$;
REVOKE ALL ON FUNCTION public.twin_day_messages(date) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.twin_day_messages(date) TO service_role;

-- ── 9. Highlights, for the Book and the control room ────────────────────
CREATE OR REPLACE FUNCTION public.twin_highlights_recent(p_limit integer DEFAULT 30)
RETURNS TABLE (id uuid, day date, kind text, text text, score real, source text, message_id uuid)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT h.id, h.day, h.kind, h.text, h.score, h.source, h.message_id
  FROM public.message_highlights h
  WHERE public.is_partner(auth.uid())
  ORDER BY h.day DESC, h.score DESC
  LIMIT greatest(coalesce(p_limit, 30), 1);
$$;
REVOKE ALL ON FUNCTION public.twin_highlights_recent(integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.twin_highlights_recent(integer) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.twin_highlights_day(p_day date)
RETURNS TABLE (id uuid, kind text, text text, score real, message_id uuid)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT h.id, h.kind, h.text, h.score, h.message_id
  FROM public.message_highlights h
  WHERE h.day = p_day
    AND public.is_partner(auth.uid())
  ORDER BY h.score DESC
  LIMIT 20;
$$;
REVOKE ALL ON FUNCTION public.twin_highlights_day(date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.twin_highlights_day(date) TO authenticated, service_role;

-- ── 10. Nightly bookkeeping ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.twin_nightly_log(
  p_days integer,
  p_highlights integer DEFAULT 0,
  p_facts_heuristic integer DEFAULT 0,
  p_facts_llm integer DEFAULT 0,
  p_llm_calls integer DEFAULT 0,
  p_tokens integer DEFAULT 0,
  p_note text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  saved public.twin_nightly_runs%ROWTYPE;
BEGIN
  INSERT INTO public.twin_nightly_runs (days, highlights, facts_heuristic, facts_llm, llm_calls, tokens, note)
  VALUES (greatest(coalesce(p_days, 7), 1), coalesce(p_highlights, 0), coalesce(p_facts_heuristic, 0),
          coalesce(p_facts_llm, 0), coalesce(p_llm_calls, 0), coalesce(p_tokens, 0), p_note)
  RETURNING * INTO saved;

  RETURN to_jsonb(saved);
END;
$$;
REVOKE ALL ON FUNCTION public.twin_nightly_log(integer, integer, integer, integer, integer, integer, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.twin_nightly_log(integer, integer, integer, integer, integer, integer, text) TO service_role;

-- Is a sweep allowed now? Free, so the client can ask cheaply before spending.
-- `p_force` is honoured for the owner only (a button in the control room).
CREATE OR REPLACE FUNCTION public.twin_nightly_state(p_force boolean DEFAULT false)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  cfg public.twin_config%ROWTYPE;
  last_run public.twin_nightly_runs%ROWTYPE;
  mins numeric;
BEGIN
  IF NOT coalesce(public.is_partner(auth.uid()), false) THEN RETURN NULL; END IF;

  SELECT * INTO cfg FROM public.twin_config WHERE id = 1;
  SELECT * INTO last_run FROM public.twin_nightly_runs ORDER BY ran_at DESC LIMIT 1;

  mins := CASE WHEN last_run.ran_at IS NULL THEN NULL
               ELSE extract(epoch FROM (now() - last_run.ran_at)) / 60.0 END;

  RETURN jsonb_build_object(
    'allowed', coalesce(mins IS NULL OR mins >= 180 OR (p_force AND auth.uid() = cfg.owner_user_id), true),
    'reason', CASE WHEN mins IS NULL THEN 'never_run'
                   WHEN mins >= 180 THEN 'due'
                   ELSE 'too_soon' END
              || CASE WHEN p_force AND auth.uid() = cfg.owner_user_id THEN '+forced' ELSE '' END,
    'last_run_at', last_run.ran_at,
    'minutes_since', round(mins),
    'last_run', to_jsonb(last_run),
    'can_force', auth.uid() = cfg.owner_user_id
  );
END;
$$;
REVOKE ALL ON FUNCTION public.twin_nightly_state(boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.twin_nightly_state(boolean) TO authenticated, service_role;

-- ── 11. Verify ──────────────────────────────────────────────────────────
--   select public.twin_memory_stats();
--   select * from public.twin_memory_search('birthday', null, 5);
--   select public.twin_memory_upsert('<subject-uuid>', 'loves filter coffee', 'likes', 'manual', 1.0, 0.8);
